'use strict';
const BRAND='TRAINR';
const $=id=>document.getElementById(id),uid=()=>crypto.randomUUID();
const KEY='trainr-v2',DAYS=['Montag','Dienstag','Mittwoch','Donnerstag','Freitag','Samstag','Sonntag'];
const LABELS={field:'Nur Feldspieler',keeper:'Nur Torwart',both:'Feldspieler & Torwart'};
const initial=()=>({version:2,profile:null,custom:[],plans:[{id:uid(),name:'Meine erste Einheit',blocks:[],people:12,slot:null,focus:'Alle'}],selected:null});
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function text(x,n){return typeof x==='string'&&x.trim()&&x.length<=n;}
function integer(x,a,b){return Number.isInteger(x)&&x>=a&&x<=b;}
function safeURL(x){if(!x)return true;try{return new URL(x).protocol==='https:';}catch{return false;}}
function validate(x){
 if(!x||x.version!==2||!Array.isArray(x.custom)||x.custom.length>500||!Array.isArray(x.plans)||!x.plans.length||x.plans.length>100)throw Error('Ungültiges Stufe-2-Backup.');
 if(x.profile){const p=x.profile;if(!LABELS[p.type]||!AGES.includes(p.age)||!Array.isArray(p.slots)||!p.slots.length||p.slots.length>7)throw Error('Ungültiges Trainerprofil.');const days=new Set();for(const s of p.slots){if(!integer(s.day,0,6)||days.has(s.day)||!/^\d\d:\d\d$/.test(s.start)||!/^\d\d:\d\d$/.test(s.end)||time(s.start)<0||time(s.end)<0||time(s.end)<=time(s.start))throw Error('Ungültige Wochenzeiten.');days.add(s.day);}}
 const ids=new Set(SEED.map(e=>e.id));for(const e of x.custom){if(!text(e.id,100)||ids.has(e.id)||!text(e.name,80)||!TAGS.includes(e.tag)||!LABELS[e.type]||!Array.isArray(e.ages)||!e.ages.length||e.ages.some(a=>!AGES.includes(a))||!integer(e.min,1,100)||!integer(e.max,e.min,100)||!integer(e.minutes,1,120)||!text(e.description,1000)||!text(e.coaching,1000)||!Array.isArray(e.equipment)||e.equipment.length>20||e.equipment.some(a=>!Array.isArray(a)||!text(a[0],100)||!integer(a[1],1,100))||typeof e.url!=='string'||e.url.length>500||!safeURL(e.url))throw Error('Ungültige eigene Übung.');ids.add(e.id);}
 const pids=new Set(),bids=new Set();for(const p of x.plans){if(!text(p.id,100)||pids.has(p.id)||!text(p.name,80)||!integer(p.people,1,100)||!['Alle',...TAGS].includes(p.focus)||!(p.slot===null||integer(p.slot,0,6))||!Array.isArray(p.blocks)||p.blocks.length>100)throw Error('Ungültiger Plan.');
 if(p.age!==undefined&&!AGES.includes(p.age))throw Error('Ungültige Plan-Altersklasse.');pids.add(p.id);for(const b of p.blocks){if(!text(b.id,100)||bids.has(b.id)||!ids.has(b.exerciseId)||!integer(b.minutes,1,120))throw Error('Ungültiger Block.');bids.add(b.id);}}
 x.selected=pids.has(x.selected)?x.selected:x.plans[0].id;return x;
}
function time(s){const [h,m]=s.split(':').map(Number);return integer(h,0,23)&&integer(m,0,59)?h*60+m:-1;}
let storageOK=true,state;
try{const raw=localStorage.getItem(KEY);state=raw?validate(JSON.parse(raw)):initial();}catch{state=initial();storageOK=false;}
state.selected=state.selected||state.plans[0].id;
const exercise=id=>[...SEED,...state.custom].find(e=>e.id===id),plan=()=>state.plans.find(p=>p.id===state.selected);
let timerIndex=0,remaining=0,deadline=null,tick=null,audio=null,noticeTimer;
function notify(s){$('status').textContent=s;$('status').classList.remove('hidden');clearTimeout(noticeTimer);noticeTimer=setTimeout(()=>$('status').classList.add('hidden'),4500);}
function save(){try{localStorage.setItem(KEY,JSON.stringify(state));storageOK=true;}catch{storageOK=false;notify('Speichern nicht möglich. Jetzt Backup sichern.');}}
const options=(arr)=>arr.map(v=>`<option>${esc(v)}</option>`).join('');
$('filter').innerHTML=options(['Alle Schwerpunkte',...TAGS]);$('focus').innerHTML=options(['Alle',...TAGS]);$('exTag').innerHTML=options(TAGS);$('exAge').innerHTML=options(AGES);$('ageFilter').innerHTML=options(['Mein Alter','Alle Altersklassen',...AGES]);
function slot(){return state.profile?.slots.find(s=>s.day===plan().slot)||state.profile?.slots[0];}
function fit(e,n=plan().people){let groups=0;for(let g=1;g<=n;g++)if(n>=g*e.min&&n<=g*e.max){groups=g;break;}return groups;}
function reason(e){const g=fit(e),s=slot(),total=plan().blocks.reduce((a,b)=>a+b.minutes,0),left=s?time(s.end)-time(s.start)-total:999;return `${g?`${g} Gruppe${g>1?'n':''} für ${plan().people} Spieler`:'Teilnehmerzahl passt nicht'} · ${e.minutes<=left?'passt in Restzeit':'länger als Restzeit'}${plan().focus===e.tag?' · dein Schwerpunkt':''}${plan().blocks.some(b=>b.exerciseId===e.id)?' · schon im Plan':''}`;}
function score(e){return (fit(e)?100:0)+(plan().focus===e.tag?40:0)+(e.minutes<=Math.max(0,(slot()?time(slot().end)-time(slot().start):90)-plan().blocks.reduce((a,b)=>a+b.minutes,0))?20:0)-(plan().blocks.some(b=>b.exerciseId===e.id)?30:0);}
function renderCards(){const q=$('search').value.toLowerCase(),f=$('filter').value,t=$('typeFilter').value,age=$('ageFilter').value==='Mein Alter'?state.profile?.age:$('ageFilter').value;let list=[...SEED,...state.custom].filter(e=>(f==='Alle Schwerpunkte'||e.tag===f)&&`${e.name} ${e.description} ${e.equipment.map(a=>a[0])}`.toLowerCase().includes(q)&&(age==='Alle Altersklassen'||!age||e.ages.includes(age))&&(t==='all'||(t==='profile'?(state.profile?.type==='both'||e.type===state.profile?.type):e.type===t)));if($('smart').checked)list.sort((a,b)=>score(b)-score(a)||a.name.localeCompare(b.name));$('suggestionNote').textContent=`${list.length} von ${SEED.length+state.custom.length} Übungen · Regeln statt KI: Alter und Trainerart filtern; Gruppengröße, Restzeit und Schwerpunkt sortieren. Keine automatische Plan-Erstellung.`;
 $('cards').innerHTML=list.length?list.map(e=>`<article class="card" draggable="true" data-drag="${esc(e.id)}"><span class="tag">${esc(e.tag)}</span><h3>${esc(e.name)}</h3><p>${esc(e.description)}</p><div class="meta"><span>◷ ${e.minutes} Min</span><span>${e.min===e.max?e.min:`${e.min}-${e.max}`} Spieler / Gruppe</span><span>ab ${esc(e.ages[0])}</span></div><p><strong>Material je Gruppe:</strong> ${e.equipment.map(a=>`${a[1]} ${esc(a[0])}`).join(', ')}</p><p class="reason">${esc(reason(e))}</p><div class="row"><button data-detail="${esc(e.id)}" class="textbutton">Coaching & Quelle ↗</button><button data-add="${esc(e.id)}" class="primary">+ In den Plan</button></div></article>`).join(''):'<p class="empty">Keine passende Übung. Filter ändern oder eigene Übung anlegen. Bei Bambini keine festen Keeperübungen empfohlen.</p>';
}
function requirements(){const items={};for(const b of plan().blocks){const e=exercise(b.exerciseId),g=fit(e)||1;for(const [name,count]of e.equipment)items[name]=Math.max(items[name]||0,count*g);}return items;}
function render(){const p=plan(),s=slot(),total=p.blocks.reduce((a,b)=>a+b.minutes,0),target=s?time(s.end)-time(s.start):0;$('plans').innerHTML=state.plans.map(x=>`<option value="${esc(x.id)}" ${p.id===x.id?'selected':''}>${esc(x.name)}</option>`).join('');$('planName').value=p.name;$('participants').value=p.people;$('focus').value=p.focus;$('sessionDay').innerHTML=(state.profile?.slots||[]).map(x=>`<option value="${x.day}" ${s?.day===x.day?'selected':''}>${DAYS[x.day]} · ${x.start}-${x.end}</option>`).join('');$('total').textContent=`${total} MIN`;$('profileSummary').textContent=state.profile?`${LABELS[state.profile.type]} · ${state.profile.age} · ${state.profile.slots.map(x=>DAYS[x.day]+' '+x.start+'-'+x.end).join(' / ')}`:'';
 $('planSummary').textContent=`${p.age||state.profile?.age||''} · ${p.people} Spieler (ohne Trainer) · ${s?`${target} Min verfügbar · ${total>target?total-target+' Min zu lang':target-total+' Min noch frei'}`:'Trainingstag im Profil wählen'}${state.profile?.age==='Bambini'&&state.profile?.type==='keeper'?' · Bambini: besser allgemeine Ballspiele statt Spezialisierung.':''}`;
 $('blocks').innerHTML=p.blocks.length?p.blocks.map((b,i)=>{const e=exercise(b.exerciseId),g=fit(e);return `<li class="block ${i===timerIndex?'is-current':''}" draggable="true" data-block="${b.id}"><div class="blockhead"><span class="num">${i+1}</span><strong>${esc(e.name)}</strong><input class="duration" type="number" min="1" max="120" value="${b.minutes}" data-duration="${b.id}" aria-label="Minuten für ${esc(e.name)}"><span>Min</span></div><p class="subtle ${g?'':'fit-warning'}">${g?g+' parallele Gruppe(n)':`⚠ ${p.people} Spieler passen nicht in Gruppen von ${e.min}-${e.max}`} ${state.profile&&!e.ages.includes(plan().age||state.profile.age)?' · ⚠ Altersklasse prüfen':''}</p><div class="blockactions"><button data-move="${i}" data-dir="-1" ${i===0?'disabled':''} aria-label="Block ${i+1} nach oben">↑</button><button data-move="${i}" data-dir="1" ${i===p.blocks.length-1?'disabled':''} aria-label="Block ${i+1} nach unten">↓</button><button data-remove="${b.id}">Entfernen</button></div></li>`;}).join(''):'<li class="empty">Übungen hierher ziehen oder + In den Plan wählen.</li>';
 const eq=requirements();$('equipmentSummary').innerHTML=`<strong>Material für die Einheit</strong><p>${Object.entries(eq).map(([k,v])=>`${v} ${esc(k)}`).join(' · ')||'Noch keine Übungen.'}</p><p class="subtle">Höchstbedarf pro Block, nicht Summe aller Blöcke. Parallele Gruppen sind eingerechnet. Bei ⚠ Gruppengröße zuerst anpassen. Keeperübungen mit 1-2 Spielern brauchen zusätzlich einen Helfer pro Gruppe; Trainer zählen nicht als Spieler.</p>`;renderCards();renderTimer();renderPrint();}
let setupStep=0,draft=null;
function setup(){draft=JSON.parse(JSON.stringify(state.profile||{type:'field',age:'E-Jugend',slots:[{day:0,start:'17:00',end:'18:30'}]}));setupStep=0;showStep();}
function showStep(){$('onboarding').classList.remove('hidden');$('mainNav').classList.add('hidden');$('board').classList.add('hidden');$('info').classList.add('hidden');$('stepTitle').textContent=`${setupStep+1} / 3 · ${['Trainerart & Altersklasse','Trainingstage','Trainingszeiten'][setupStep]}`;$('setupBack').disabled=setupStep===0;$('setupNext').textContent=setupStep===2?'Bibliothek öffnen':'Weiter';$('setupError').textContent='';
 $('stepBody').innerHTML=setupStep===0?`<div class="choices">${Object.entries(LABELS).map(([k,v])=>`<label class="choice"><input type="radio" name="coachType" value="${k}" ${draft.type===k?'checked':''}> ${v}</label>`).join('')}</div><label for="coachAge">Altersklasse</label><select id="coachAge">${AGES.map(a=>`<option ${draft.age===a?'selected':''}>${a}</option>`).join('')}</select><p class="subtle">Bambini bis Männer. Keine Spielernamen. Die Vorschläge passen sich deinem Profil an.</p>`:setupStep===1?DAYS.map((d,i)=>`<label><input type="checkbox" name="day" value="${i}" style="width:auto" ${draft.slots.some(s=>s.day===i)?'checked':''}> ${d}</label>`).join(''):`<p class="subtle">Beginn und Ende pro ausgewähltem Tag. Endzeit am selben Tag nach Beginn.</p>${draft.slots.map(s=>`<div class="dayrow"><strong>${DAYS[s.day]}</strong><label>Von<input type="time" id="start-${s.day}" required value="${s.start}"></label><label>Bis<input type="time" id="end-${s.day}" required value="${s.end}"></label></div>`).join('')}`;}
$('setupBack').onclick=()=>{setupStep--;showStep();};$('setupForm').onsubmit=ev=>{ev.preventDefault();if(setupStep===0){draft.type=document.querySelector('[name=coachType]:checked').value;draft.age=$('coachAge').value;}else if(setupStep===1){const days=[...document.querySelectorAll('[name=day]:checked')].map(x=>Number(x.value));if(!days.length){$('setupError').textContent='Mindestens einen Trainingstag auswählen.';return;}draft.slots=days.map(day=>draft.slots.find(x=>x.day===day)||{day,start:'17:00',end:'18:30'});}else{for(const s of draft.slots){s.start=$('start-'+s.day).value;s.end=$('end-'+s.day).value;if(time(s.start)<0||time(s.end)<=time(s.start)){$('setupError').textContent='Die Endzeit muss nach dem Beginn liegen.';return;}}state.profile=draft;for(const p of state.plans)if(!draft.slots.some(s=>s.day===p.slot))p.slot=draft.slots[0].day;save();$('onboarding').classList.add('hidden');$('mainNav').classList.remove('hidden');$('board').classList.remove('hidden');render();return;}setupStep++;showStep();};$('settings').onclick=setup;
function add(id){const e=exercise(id);if(!e)return;if(plan().blocks.length>=100)return notify('Maximal 100 Blöcke.');plan().blocks.push({id:uid(),exerciseId:id,minutes:e.minutes});resetTimer();save();render();notify('Übung im Plan.');}
function download(name,body,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([body],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
function summaryText(){const p=plan(),s=slot();return `${BRAND} · ${p.name}\n${plan().age||state.profile?.age||''} · ${LABELS[state.profile?.type]||''}\n${s?DAYS[s.day]+' '+s.start+'-'+s.end:''}\n${p.people} Spieler (ohne Trainer)\n${p.blocks.reduce((a,b)=>a+b.minutes,0)} Minuten\n\n`+p.blocks.map((b,i)=>{const e=exercise(b.exerciseId);return `${i+1}. ${e.name} · ${b.minutes} Minuten\n${fit(e)?fit(e)+' parallele Gruppe(n)':'ACHTUNG: Gruppengröße anpassen'}\n${e.description}\nCoaching: ${e.coaching}\nMaterial je Gruppe: ${e.equipment.map(a=>a[1]+' '+a[0]).join(', ')}\nQuelle: ${e.url||'Eigene Übung'}\n${state.profile&&!e.ages.includes(plan().age||state.profile.age)?'ACHTUNG: Altersklasse prüfen.\n':''}`;}).join('\n')+'\nMaterialübersicht (Höchstbedarf, parallele Gruppen):\n'+Object.entries(requirements()).map(([k,v])=>v+' '+k).join('\n')+'\nKeeperübungen mit 1-2 Spielern: zusätzlicher Helfer pro Gruppe. Bei unpassender Gruppengröße sind Mengen vorläufig. Altersgrenzen, Zeit und Menge sind Vorschläge. Sichere Falltechnik und weicher Boden sind Pflicht. Keine frühen Spezialisierungsvorgaben für Bambini.';}
function renderPrint(){$('printArea').innerHTML=`<h1>${esc(BRAND)} · Trainingsplan</h1><pre style="white-space:pre-wrap;font:14px/1.6 system-ui">${esc(summaryText())}</pre>`;}
function stopTimer(){deadline=null;clearInterval(tick);tick=null;}
function resetTimer(){stopTimer();timerIndex=Math.min(timerIndex,Math.max(0,plan().blocks.length-1));remaining=plan().blocks[timerIndex]?.minutes*60||0;renderTimer();}
function renderTimer(){const b=plan().blocks[timerIndex];$('timerName').textContent=b?exercise(b.exerciseId).name:'Füge zuerst eine Übung hinzu';$('clock').textContent=`${String(Math.floor(remaining/60)).padStart(2,'0')}:${String(remaining%60).padStart(2,'0')}`;$('timerMeta').textContent=b?`Block ${timerIndex+1} / ${plan().blocks.length} · ${b.minutes} Minuten`:'';$('startTimer').textContent=deadline?'Pause':remaining?'Start':'Nochmal';$('startTimer').disabled=!b;$('nextBlock').disabled=!b||timerIndex>=plan().blocks.length-1;}
function updateClock(){if(!deadline)return;remaining=Math.max(0,Math.ceil((deadline-Date.now())/1000));if(!remaining){stopTimer();try{const o=audio.createOscillator(),g=audio.createGain();o.connect(g);g.connect(audio.destination);g.gain.value=.08;o.frequency.value=660;o.start();o.stop(audio.currentTime+.4);}catch{}notify('Block fertig. Kurz sammeln, dann weiter.');}renderTimer();}
$('startTimer').onclick=()=>{if(deadline){updateClock();stopTimer();renderTimer();return;}if(!remaining)remaining=plan().blocks[timerIndex].minutes*60;try{audio=audio||new(window.AudioContext||window.webkitAudioContext)();audio.resume();}catch{}deadline=Date.now()+remaining*1000;tick=setInterval(updateClock,200);renderTimer();};
$('resetTimer').onclick=resetTimer;$('nextBlock').onclick=()=>{timerIndex++;resetTimer();render();};document.addEventListener('visibilitychange',updateClock);
$('blocks').onclick=ev=>{const remove=ev.target.closest('[data-remove]'),move=ev.target.closest('[data-move]');if(remove){plan().blocks=plan().blocks.filter(b=>b.id!==remove.dataset.remove);}else if(move){const i=Number(move.dataset.move),j=i+Number(move.dataset.dir);if(j<0||j>=plan().blocks.length)return;[plan().blocks[i],plan().blocks[j]]=[plan().blocks[j],plan().blocks[i]];}else return;resetTimer();save();render();};
$('blocks').onchange=ev=>{if(!ev.target.matches('[data-duration]'))return;const n=Number(ev.target.value),b=plan().blocks.find(b=>b.id===ev.target.dataset.duration);if(!Number.isInteger(n)||n<1||n>120){notify('Bitte 1 bis 120 ganze Minuten wählen.');render();return;}b.minutes=n;resetTimer();save();render();};
$('plans').onchange=()=>{state.selected=$('plans').value;timerIndex=0;resetTimer();save();render();};$('planName').onchange=()=>{plan().name=$('planName').value.trim()||'Meine Einheit';save();render();};
$('newPlan').onclick=()=>{if(state.plans.length>=100)return notify('Maximal 100 Pläne.');const p={id:uid(),name:'Neue Einheit',blocks:[],people:plan().people,slot:plan().slot,focus:'Alle'};state.plans.push(p);state.selected=p.id;timerIndex=0;resetTimer();save();render();};
$('deletePlan').onclick=()=>{if(!confirm(`Plan "${plan().name}" löschen?`))return;state.plans=state.plans.filter(p=>p.id!==state.selected);if(!state.plans.length)state.plans=[{id:uid(),name:'Meine Einheit',blocks:[],people:12,slot:state.profile?.slots[0].day??null,focus:'Alle'}];state.selected=state.plans[0].id;timerIndex=0;resetTimer();save();render();};
$('search').oninput=renderCards;$('filter').onchange=renderCards;
for(const b of document.querySelectorAll('[data-tab]'))b.onclick=()=>{for(const t of ['board','info'])$(t).classList.toggle('hidden',t!==b.dataset.tab);document.querySelectorAll('[data-tab]').forEach(n=>n.classList.toggle('active',n===b));};
$('newExercise').onclick=()=>{$('exerciseForm').reset();$('formError').textContent='';$('exerciseDialog').showModal();};document.querySelectorAll('.closeDialog').forEach(b=>b.onclick=()=>b.closest('dialog').close());
$('exerciseForm').onsubmit=ev=>{ev.preventDefault();const e={id:'custom-'+uid(),name:$('exName').value.trim(),type:$('exType').value,ages:AGES.slice(AGES.indexOf($('exAge').value)),tag:$('exTag').value,description:$('exDescription').value.trim(),equipment:[[$('exMaterial').value.trim(),1]],min:Number($('exPeople').value),max:Number($('exPeople').value),minutes:Number($('exMinutes').value),url:$('exSource').value.trim(),coaching:'Eigene Übung. Altersklasse, Aufbau und Belastung selbst prüfen.',custom:true};try{validate({...state,custom:[...state.custom,e]});state.custom.push(e);save();render();$('exerciseDialog').close();notify('Eigene Übung gespeichert.');}catch(err){$('formError').textContent=err.message;}};
$('export').onclick=()=>{const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='trainr-backup.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);};
$('import').onchange=async ev=>{const file=ev.target.files[0];if(!file)return;try{if(file.size>2000000)throw Error('Backup zu groß (max. 2 MB).');const next=validate(JSON.parse(await file.text()));if(confirm(`${next.plans.length} Pläne und ${next.custom.length} eigene Übungen wiederherstellen? Deine aktuellen Daten werden ersetzt.`)){stopTimer();state=next;timerIndex=0;resetTimer();save();render();notify('Backup wiederhergestellt.');}}catch(err){notify('Import abgelehnt: '+err.message);}finally{ev.target.value='';}};
$('printPlan').onclick=()=>window.print();
$('jumpPlan').onclick=()=>{document.querySelector('[data-tab=board]').click();$('planner').scrollIntoView({behavior:'smooth',block:'start'});};
let installPrompt;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e;$('install').classList.remove('hidden');});$('install').onclick=async()=>{await installPrompt.prompt();installPrompt=null;$('install').classList.add('hidden');};
if('serviceWorker'in navigator&&location.protocol!=='file:')navigator.serviceWorker.register('./sw.js',{updateViaCache:'none'}).catch(()=>notify('Offline-Modus nicht verfügbar. Sichere Adresse oder localhost erforderlich.'));
resetTimer();render();if(!state.profile)setup();if(!storageOK)$('storageWarning').textContent='Lokaler Speicher nicht verfügbar oder gespeicherte Daten ungültig. Backup sichern; vorhandene Browserdaten wurden nicht überschrieben.';

$('cards').onclick=ev=>{const a=ev.target.closest('[data-add]'),d=ev.target.closest('[data-detail]');if(a)add(a.dataset.add);if(d){const e=exercise(d.dataset.detail);$('detailContent').innerHTML=`<span class="tag">${esc(e.tag)}</span><h2>${esc(e.name)}</h2><p>${esc(e.description)}</p><h3>Aufbau & Material</h3><p>${e.equipment.map(a=>a[1]+' '+esc(a[0])).join(', ')} je Gruppe</p><h3>Coaching</h3><p>${esc(e.coaching)}</p><p>Geeignet ab ${esc(e.ages[0])} (redaktioneller Vorschlag)</p>${e.url?`<a href="${esc(e.url)}" target="_blank" rel="noopener noreferrer">Quelle öffnen ↗</a>`:'Eigene Übung ohne Quelle.'}<p class="subtle">Eigene Kurzfassung / Variante, keine offizielle DFB-Einheit. Belastung und Abstände an Können anpassen.</p>`;$('detailDialog').showModal();}};
for(const id of ['typeFilter','ageFilter','smart'])$(id).onchange=renderCards;
$('participants').onchange=()=>{const n=Number($('participants').value);if(!integer(n,1,100)){notify('1-100 Spieler eintragen.');render();return;}plan().people=n;save();render();};$('focus').onchange=()=>{plan().focus=$('focus').value;save();render();};$('sessionDay').onchange=()=>{plan().slot=Number($('sessionDay').value);save();render();};
let dragging=null;document.addEventListener('dragstart',ev=>{const c=ev.target.closest('[data-drag]'),b=ev.target.closest('[data-block]');if(c||b){dragging=c?{exercise:c.dataset.drag}:{block:b.dataset.block};ev.dataTransfer.setData('text/plain',JSON.stringify(dragging));ev.dataTransfer.effectAllowed='copyMove';}});
$('blocks').ondragover=ev=>{ev.preventDefault();$('blocks').classList.add('dropactive');};$('blocks').ondragleave=()=>{$('blocks').classList.remove('dropactive');};$('blocks').ondrop=ev=>{ev.preventDefault();$('blocks').classList.remove('dropactive');if(!dragging)return;if(dragging.exercise){add(dragging.exercise);}else{const p=plan(),i=p.blocks.findIndex(b=>b.id===dragging.block),target=ev.target.closest('[data-block]'),j=target?p.blocks.findIndex(b=>b.id===target.dataset.block):p.blocks.length-1;if(i>=0&&j>=0){const [b]=p.blocks.splice(i,1);p.blocks.splice(j,0,b);resetTimer();save();render();}}dragging=null;};document.addEventListener('dragend',()=>{dragging=null;$('blocks').classList.remove('dropactive');});
$('exportPlan').onclick=()=>download('trainr-plan.txt',summaryText(),'text/plain;charset=utf-8');
$('exportCsv').onclick=()=>{const csv=v=>'"'+String(v).replace(/"/g,'""')+'"',p=plan(),s=slot();const rows=[['Plan',p.name],['Altersklasse',plan().age||state.profile?.age||''],['Trainingstag',s?DAYS[s.day]+' '+s.start+'-'+s.end:''],['Spieler ohne Trainer',p.people],['Block','Übung','Minuten','Gruppen','Beschreibung','Quelle'],...p.blocks.map((b,i)=>{const e=exercise(b.exerciseId);return [i+1,e.name,b.minutes,fit(e)||'Anpassen',e.description,e.url]}),['Material','Höchstbedarf'],...Object.entries(requirements()),['Hinweis','Keeper mit 1-2 Spielern: Helfer pro Gruppe zusätzlich; Mengen bei unpassender Gruppe vorläufig.']];download('trainr-plan.csv','\uFEFF'+rows.map(r=>r.map(v=>csv(typeof v==='string'&&/^[=+@-]/.test(v)?"'"+v:v)).join(';')).join('\r\n'),'text/csv;charset=utf-8');};
document.title=BRAND;document.querySelectorAll('[data-brand]').forEach(n=>n.textContent=BRAND);
