'use strict';
const $=id=>document.getElementById(id);
const source={gym:'https://www.dfb-akademie.de/teil-2-gymnastik/-/id-11011649',tech:'https://www.dfb-akademie.de/teil-4-grundtechniken-der-torhueterinnen/-/id-11011651',dive:'https://www.soccerdrills.de/trainingsuebungen/torwart/uebungen/erste-hechter/767/',pass:'https://www.torwart.de/magazin/training/grundtechniken-mit-thomas-schlieck/der-torwart-als-11-feldspieler.html'};
const SEED=[
{id:'warm',name:'Ballgefühl zum Start',tag:'Aufwärmen',description:'Locker bewegen, den Ball prellen und kontrolliert fangen. Jeder arbeitet mit seinem eigenen Ball und genügend Abstand.',material:'2 Bälle, freie Fläche',people:2,minutes:2,url:source.gym,coaching:'Leicht beginnen. Qualität vor Tempo. Anfängeranpassung als Erwärmung.'},
{id:'ready',name:'Achterkreise & Torwart-Foto',tag:'Grundhaltung',description:'Ball in einer Acht um die Beine führen. Danach ablegen, zwei kleine Seitwärtsschritte machen und vor einem leichten Fangball bereit stehen.',material:'2 Bälle, freie Fläche',people:3,minutes:3,url:source.gym,coaching:'Knie weich, Oberkörper leicht vor, Hände vor dem Körper. Nicht tief sitzen. Vor dem Zuspiel zur Ruhe kommen. Nur einen Punkt auf einmal korrigieren.'},
{id:'catch',name:'Schaufel & weiche Hände',tag:'Fangen',description:'Trainer spielt langsame Rollbälle, danach sanfte Würfe auf obere Brusthöhe. Beide Keeper wechseln nach kurzen Serien von 3-4 Bällen.',material:'1-2 Bälle, optional Hütchen',people:3,minutes:4,url:source.tech,coaching:'Flach: Körper hinter den Ball, Hände tief, Ball sichern. Oben: Hände hinter den Ball, Daumen/Zeigefinger ungefähr als Dreieck, weich nachgeben. Halbhohe Bälle brauchen eine andere Fangtechnik.'},
{id:'floor',name:'Erste Hechter: Bodenstufe',tag:'Hechten',description:'Im niedrigen Kniestand liegt der Ball seitlich und leicht vor dem Kind. Kontrolliert über die Hüfte auf die Seite gehen. Erst ruhender Ball, dann langsam gerollt; nach zwei Aktionen wechseln.',material:'1 Ball, weicher ebener Rasen oder geeignete Matte',people:3,minutes:3,url:source.dive,coaching:'Ballnahe Hand hinter den Ball, andere Hand oben drauf. Nicht auf dem Ellenbogen abstützen, nicht nach hinten rollen. Beide Seiten üben. Bei Angst, Schmerz oder ungeeignetem Boden stoppen.'},
{id:'stand',name:'Flacher Ball & Abkippen',tag:'Hechten',description:'Nur nach sicherer Bodenstufe: aus der Grundhaltung einen kleinen Schritt schräg nach vorn zum seitlich gerollten Ball machen und kontrolliert auf die Seite abkippen. Je 2-3 Wiederholungen pro Seite.',material:'1 Ball, weicher ebener Rasen oder geeignete Matte',people:3,minutes:3,url:source.tech,coaching:'Kein hoher Flugsprung, kein Riesenschritt. Erst zeigen. Nur angstfrei und mit sicherer Landetechnik steigern; bei Unsicherheit erfahrenen Torwarttrainer hinzunehmen.'},
{id:'pass',name:'Rückpass-Dreieck',tag:'Annehmen + Passen',description:'Trainer links, Keeper A vor dem Tor, Keeper B rechts, etwa 5-7 m auseinander. A nimmt den Rückpass schräg nach vorn mit und passt zu B. B spielt zurück zum Trainer. Nach vier Pässen wechseln.',material:'1 Ball, 2 Hütchen, optional 1 Tor',people:3,minutes:5,url:source.pass,coaching:'Vor der Annahme zum Ziel schauen. Erster Kontakt vom Tor weg und in Reichweite. Präzision vor Härte, beide Seiten üben. Eigenes Spielziel: Pass durch ein 1-1,5 m breites Hütchentor.'}
];
const KEY='keeperboard-v1';
const uid=()=>crypto.randomUUID();
const initial=()=>({version:1,custom:[],plans:[{id:uid(),name:'E-Jugend · Technikstart',blocks:SEED.map(x=>({id:uid(),exerciseId:x.id,minutes:x.minutes}))}],selected:null});
let storageOK=true,state;
function validText(x,max){return typeof x==='string'&&x.trim().length>0&&x.length<=max;}
function safeURL(x){if(!x)return true;try{return new URL(x).protocol==='https:';}catch{return false;}}
function validate(x){
 if(!x||x.version!==1||!Array.isArray(x.custom)||!Array.isArray(x.plans)||x.custom.length>500||!x.plans.length||x.plans.length>100)throw Error('Unbekanntes oder zu großes Backup.');
 const tags=['Aufwärmen','Grundhaltung','Fangen','Hechten','Annehmen + Passen'];
 const allIds=new Set(SEED.map(e=>e.id));
 for(const e of x.custom){if(!validText(e.id,100)||allIds.has(e.id)||!validText(e.name,80)||!validText(e.description,1000)||!validText(e.material,160)||!tags.includes(e.tag)||!Number.isInteger(e.people)||e.people<1||e.people>100||!Number.isInteger(e.minutes)||e.minutes<1||e.minutes>120||typeof e.url!=='string'||e.url.length>500||!safeURL(e.url))throw Error('Ungültige Übung im Backup.');allIds.add(e.id);}
 const pids=new Set(),bids=new Set();
 for(const p of x.plans){if(!validText(p.id,100)||pids.has(p.id)||!validText(p.name,80)||!Array.isArray(p.blocks)||p.blocks.length>100)throw Error('Ungültiger Plan im Backup.');pids.add(p.id);for(const b of p.blocks){if(!validText(b.id,100)||bids.has(b.id)||!allIds.has(b.exerciseId)||!Number.isInteger(b.minutes)||b.minutes<1||b.minutes>120)throw Error('Ungültiger Trainingsblock.');bids.add(b.id);}}
 return {version:1,custom:x.custom.map(e=>({id:e.id,name:e.name,tag:e.tag,description:e.description,material:e.material,people:e.people,minutes:e.minutes,url:e.url,coaching:'Eigene Übung. Aufbau und Belastung selbst prüfen.'})),plans:x.plans.map(p=>({id:p.id,name:p.name,blocks:p.blocks.map(b=>({id:b.id,exerciseId:b.exerciseId,minutes:b.minutes}))})),selected:pids.has(x.selected)?x.selected:x.plans[0].id};
}
try{const saved=localStorage.getItem(KEY);state=saved?validate(JSON.parse(saved)):initial();}catch{state=initial();storageOK=false;}
state.selected=state.selected||state.plans[0].id;
let timerIndex=0,remaining=0,deadline=null,tick=null,audio=null,noticeTimer;
const exercise=id=>[...SEED,...state.custom].find(e=>e.id===id);
const plan=()=>state.plans.find(p=>p.id===state.selected);
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function notify(text){$('status').textContent=text;$('status').classList.remove('hidden');clearTimeout(noticeTimer);noticeTimer=setTimeout(()=>$('status').classList.add('hidden'),4500);}
function save(){try{localStorage.setItem(KEY,JSON.stringify(state));storageOK=true;}catch{storageOK=false;notify('Speichern nicht möglich. Backup herunterladen, bevor du schließt.');}if(!storageOK)$('storageWarning').textContent='Lokaler Speicher nicht verfügbar oder alte Daten ungültig. Änderungen können verloren gehen. Jetzt ein Backup sichern.';}
function renderCards(){const q=$('search').value.toLocaleLowerCase('de'),f=$('filter').value;const list=[...SEED,...state.custom].filter(e=>(f==='Alle Schwerpunkte'||e.tag===f)&&`${e.name} ${e.description} ${e.material}`.toLocaleLowerCase('de').includes(q));$('cards').innerHTML=list.length?list.map(e=>`<article class="card"><span class="tag">${esc(e.tag)}</span><h3>${esc(e.name)}</h3><p>${esc(e.description)}</p><div class="meta"><span>◷ ${e.minutes} Min</span><span>◉ ${e.people} Personen gesamt</span></div><p><strong>Material:</strong> ${esc(e.material)}</p><div class="row"><button data-detail="${esc(e.id)}" class="textbutton">Coaching & Quelle ↗</button><button data-add="${esc(e.id)}" class="primary">+ In den Plan</button></div></article>`).join(''):'<p class="empty">Keine passende Übung. Ändere Suche oder Schwerpunkt.</p>';}
function render(){const p=plan();$('plans').innerHTML=state.plans.map(x=>`<option value="${esc(x.id)}" ${p.id===x.id?'selected':''}>${esc(x.name)}</option>`).join('');$('planName').value=p.name;$('total').textContent=`${p.blocks.reduce((s,b)=>s+b.minutes,0)} MIN`;$('blocks').innerHTML=p.blocks.length?p.blocks.map((b,i)=>`<li class="block ${i===timerIndex?'is-current':''}"><div class="blockhead"><span class="num">${i+1}</span><strong>${esc(exercise(b.exerciseId).name)}</strong><input class="duration" type="number" min="1" max="120" value="${b.minutes}" data-duration="${esc(b.id)}" aria-label="Minuten für ${esc(exercise(b.exerciseId).name)}"><span class="subtle">Min</span></div><div class="blockactions"><button data-move="${i}" data-dir="-1" aria-label="Block ${i+1} nach oben" ${i===0?'disabled':''}>↑</button><button data-move="${i}" data-dir="1" aria-label="Block ${i+1} nach unten" ${i===p.blocks.length-1?'disabled':''}>↓</button><button data-remove="${esc(b.id)}">Entfernen</button></div></li>`).join(''):'<li class="empty">Dein Plan ist leer. Füge links eine Übung hinzu.</li>';renderTimer();renderCards();}
function stopTimer(){deadline=null;clearInterval(tick);tick=null;}
function resetTimer(){stopTimer();timerIndex=Math.min(timerIndex,Math.max(0,plan().blocks.length-1));remaining=plan().blocks[timerIndex]?.minutes*60||0;renderTimer();}
function renderTimer(){const b=plan().blocks[timerIndex];$('timerName').textContent=b?exercise(b.exerciseId).name:'Füge zuerst eine Übung hinzu';$('clock').textContent=`${String(Math.floor(remaining/60)).padStart(2,'0')}:${String(remaining%60).padStart(2,'0')}`;$('timerMeta').textContent=b?`Block ${timerIndex+1} / ${plan().blocks.length} · ${b.minutes} Minuten`:'';$('startTimer').textContent=deadline?'Pause':remaining?'Start':'Nochmal';$('startTimer').disabled=!b;$('nextBlock').disabled=!b||timerIndex>=plan().blocks.length-1;}
function updateClock(){if(!deadline)return;remaining=Math.max(0,Math.ceil((deadline-Date.now())/1000));if(!remaining){stopTimer();try{const o=audio.createOscillator(),g=audio.createGain();o.connect(g);g.connect(audio.destination);g.gain.value=.08;o.frequency.value=660;o.start();o.stop(audio.currentTime+.4);}catch{}notify('Block fertig. Kurz sammeln, dann weiter.');}renderTimer();}
$('startTimer').onclick=()=>{if(deadline){updateClock();stopTimer();renderTimer();return;}if(!remaining)remaining=plan().blocks[timerIndex].minutes*60;try{audio=audio||new(window.AudioContext||window.webkitAudioContext)();audio.resume();}catch{}deadline=Date.now()+remaining*1000;tick=setInterval(updateClock,200);renderTimer();};
$('resetTimer').onclick=resetTimer;$('nextBlock').onclick=()=>{timerIndex++;resetTimer();render();};document.addEventListener('visibilitychange',updateClock);
$('cards').onclick=ev=>{const add=ev.target.closest('[data-add]'),detail=ev.target.closest('[data-detail]');if(add){if(plan().blocks.length>=100)return notify('Maximal 100 Blöcke pro Plan.');plan().blocks.push({id:uid(),exerciseId:add.dataset.add,minutes:exercise(add.dataset.add).minutes});if(plan().blocks.length===1)resetTimer();save();render();notify('Übung im Plan.');}if(detail){const e=exercise(detail.dataset.detail);$('detailContent').innerHTML=`<span class="tag">${esc(e.tag)}</span><h2>${esc(e.name)}</h2><p>${esc(e.description)}</p><p><strong>Material:</strong> ${esc(e.material)}</p><p>${e.people} Personen insgesamt · ${e.minutes} Minuten als Vorschlag</p><h3>Coaching</h3><p class="detail">${esc(e.coaching)}</p>${e.url?`<p><a target="_blank" rel="noopener noreferrer" href="${esc(e.url)}">Quelle öffnen ↗</a></p>`:'<p>Eigene Übung ohne externe Quelle.</p>'}<p class="subtle">Eigene Kurzfassung und Anfängeranpassung. Abstände und Dauer an Können und Sicherheit anpassen.</p>`;$('detailDialog').showModal();}};
$('blocks').onclick=ev=>{const remove=ev.target.closest('[data-remove]'),move=ev.target.closest('[data-move]');if(remove){plan().blocks=plan().blocks.filter(b=>b.id!==remove.dataset.remove);}else if(move){const i=Number(move.dataset.move),j=i+Number(move.dataset.dir);if(j<0||j>=plan().blocks.length)return;[plan().blocks[i],plan().blocks[j]]=[plan().blocks[j],plan().blocks[i]];}else return;resetTimer();save();render();};
$('blocks').onchange=ev=>{if(!ev.target.matches('[data-duration]'))return;const n=Number(ev.target.value),b=plan().blocks.find(b=>b.id===ev.target.dataset.duration);if(!Number.isInteger(n)||n<1||n>120){notify('Bitte 1 bis 120 ganze Minuten wählen.');render();return;}b.minutes=n;resetTimer();save();render();};
$('plans').onchange=()=>{state.selected=$('plans').value;timerIndex=0;resetTimer();save();render();};$('planName').onchange=()=>{plan().name=$('planName').value.trim()||'Meine Einheit';save();render();};
$('newPlan').onclick=()=>{if(state.plans.length>=100)return notify('Maximal 100 Pläne.');const p={id:uid(),name:'Neue Einheit',blocks:[]};state.plans.push(p);state.selected=p.id;timerIndex=0;resetTimer();save();render();};
$('deletePlan').onclick=()=>{if(!confirm(`Plan "${plan().name}" löschen?`))return;state.plans=state.plans.filter(p=>p.id!==state.selected);if(!state.plans.length)state.plans=[{id:uid(),name:'Meine Einheit',blocks:[]}];state.selected=state.plans[0].id;timerIndex=0;resetTimer();save();render();};
$('search').oninput=renderCards;$('filter').onchange=renderCards;
for(const b of document.querySelectorAll('[data-tab]'))b.onclick=()=>{for(const t of ['board','info'])$(t).classList.toggle('hidden',t!==b.dataset.tab);document.querySelectorAll('[data-tab]').forEach(n=>n.classList.toggle('active',n===b));};
$('newExercise').onclick=()=>{$('exerciseForm').reset();$('formError').textContent='';$('exerciseDialog').showModal();};document.querySelectorAll('.closeDialog').forEach(b=>b.onclick=()=>b.closest('dialog').close());
$('exerciseForm').onsubmit=ev=>{ev.preventDefault();const e={id:'custom-'+uid(),name:$('exName').value.trim(),tag:$('exTag').value,description:$('exDescription').value.trim(),material:$('exMaterial').value.trim(),people:Number($('exPeople').value),minutes:Number($('exMinutes').value),url:$('exSource').value.trim(),coaching:'Eigene Übung. Aufbau und Belastung selbst prüfen.'};try{validate({...state,custom:[...state.custom,e]});state.custom.push(e);save();render();$('exerciseDialog').close();notify('Eigene Übung gespeichert.');}catch(err){$('formError').textContent=err.message;}};
$('export').onclick=()=>{const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='keeperboard-backup.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);};
$('import').onchange=async ev=>{const file=ev.target.files[0];if(!file)return;try{if(file.size>2000000)throw Error('Backup zu groß (max. 2 MB).');const next=validate(JSON.parse(await file.text()));if(confirm(`${next.plans.length} Pläne und ${next.custom.length} eigene Übungen wiederherstellen? Deine aktuellen Daten werden ersetzt.`)){stopTimer();state=next;timerIndex=0;resetTimer();save();render();notify('Backup wiederhergestellt.');}}catch(err){notify('Import abgelehnt: '+err.message);}finally{ev.target.value='';}};
$('printPlan').onclick=()=>window.print();
$('jumpPlan').onclick=()=>{document.querySelector('[data-tab=board]').click();$('planner').scrollIntoView({behavior:'smooth',block:'start'});};
let installPrompt;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e;$('install').classList.remove('hidden');});$('install').onclick=async()=>{await installPrompt.prompt();installPrompt=null;$('install').classList.add('hidden');};
if('serviceWorker'in navigator&&location.protocol!=='file:')navigator.serviceWorker.register('./sw.js').catch(()=>notify('Offline-Modus nicht verfügbar. Sichere Adresse oder localhost erforderlich.'));
resetTimer();render();if(!storageOK)$('storageWarning').textContent='Lokaler Speicher nicht verfügbar oder gespeicherte Daten ungültig. Backup sichern; vorhandene Browserdaten wurden nicht überschrieben.';
