'use strict';
// Coach aids are local and contain no player names or external services.
const coachBox=document.createElement('section');coachBox.className='coach-tools';coachBox.innerHTML=`<h3>Vor dem Training</h3><button id="duplicatePlan">Einheit duplizieren</button><label for="coachNotes">Dein Coaching-Ziel und Notizen</label><textarea id="coachNotes" maxlength="800" placeholder="Ein klarer Coaching-Punkt, was funktioniert hat, was nächstes Mal anders wird. Keine Kindernamen."></textarea><div id="sessionCheck" class="coach-feedback" aria-live="polite"></div><details><summary>Gruppen ohne Spielernamen bilden</summary><div class="coach-grid"><label>Gruppenzahl<input id="coachGroups" type="number" min="1" max="20" value="3"></label><label>Feldspieler insgesamt<span id="groupPeople"></span></label></div><button id="makeGroups">Nummern neu mischen</button><p id="groupResult" aria-live="polite"></p><p class="subtle">Nummern an die Kinder vergeben. Keeper und Können vor Ort fair verteilen. Keine Rangfolge.</p></details>`;$('blocks').before(coachBox);
function coachNote(){return typeof plan().coachNotes==='string'?plan().coachNotes:'';}
$('coachNotes').onchange=()=>{plan().coachNotes=$('coachNotes').value.slice(0,800);save();};
$('duplicatePlan').onclick=()=>{if(state.plans.length>=100)return notify('Maximal 100 Einheiten.');const copy=structuredClone(plan());copy.id=uid();copy.name=(copy.name+' · Kopie').slice(0,80);copy.blocks.forEach(b=>b.id=uid());state.plans.push(copy);state.selected=copy.id;timerIndex=0;resetTimer();save();render();notify('Kopie erstellt. Original bleibt erhalten.');};
function balancedGroups(n,g,rng=Math.random){if(!integer(n,1,100)||!integer(g,1,Math.min(n,20)))throw Error('Gruppenzahl: 1 bis Spielerzahl, höchstens 20.');const nums=Array.from({length:n},(_,i)=>i+1);for(let i=n-1;i>0;i--){const j=Math.floor(rng()*(i+1));[nums[i],nums[j]]=[nums[j],nums[i]];}const groups=Array.from({length:g},()=>[]);nums.forEach((v,i)=>groups[i%g].push(v));return groups;}
$('makeGroups').onclick=()=>{try{$('groupResult').textContent=balancedGroups(plan().people,+$('coachGroups').value).map((g,i)=>'Gruppe '+(i+1)+': '+g.join(', ')).join(' / ');}catch(e){notify(e.message);}};
function coachCheck(){const p=plan(),s=slot(),total=p.blocks.reduce((a,b)=>a+b.minutes,0),warnings=[];if(!p.blocks.length)warnings.push('Noch keine Übungen.');if(p.blocks.some(b=>!fit(exercise(b.exerciseId))))warnings.push('Gruppengrößen passen nicht überall. Aufbau anpassen.');if(p.blocks.some(b=>!exercise(b.exerciseId).ages.includes(p.age||state.profile?.age)))warnings.push('Altersklasse einzelner Übungen prüfen.');if(s){const target=time(s.end)-time(s.start);warnings.push(total>target?(total-target)+' Minuten über der verfügbaren Zeit.':(target-total)+' Minuten für Wechsel, Trinken und freie Ergänzung.');let t=time(s.start);const fmt=x=>String(Math.floor(x/60)%24).padStart(2,'0')+':'+String(x%60).padStart(2,'0');warnings.push('Ablauf: '+p.blocks.map(b=>{const start=t;t+=b.minutes;return fmt(start)+'-'+fmt(t)+' '+exercise(b.exerciseId).name;}).join(' / '));}warnings.push('Tore sichern, Wege freihalten, Trinkpausen und Material prüfen.');$('sessionCheck').textContent=warnings.join(' ');}
const coachRender=render;render=function(){coachRender();$('coachNotes').value=coachNote();$('groupPeople').textContent=plan().people+' Spieler ohne Trainer';$('groupResult').textContent='';coachCheck();};
const coachSummary=summaryText;summaryText=function(){return coachSummary()+(coachNote()?'\n\nCoaching-Ziel / Notizen:\n'+coachNote():'');};
const coachValidate=validate;validate=function(x){coachValidate(x);for(const p of x.plans)if(p.coachNotes!==undefined&&(typeof p.coachNotes!=='string'||p.coachNotes.length>800))throw Error('Ungültige Coaching-Notizen.');return x;};
// Preserve checked material while the same plan and quantities remain in place.
const checkedMaterial=new Map();$('checkItems').addEventListener('change',ev=>{const input=ev.target;if(input.type==='checkbox')checkedMaterial.set(plan().id+'|'+input.parentElement.textContent.trim(),input.checked);});
const coachCheckRender=render;render=function(){coachCheckRender();$('checkItems').querySelectorAll('input').forEach(input=>{input.checked=checkedMaterial.get(plan().id+'|'+input.parentElement.textContent.trim())===true;});};
render();
// Editorial options, not fixed rules or official technique demonstrations.
const COACH_VARIANTS={
 'Aufwärmen':['Jedes Kind hat möglichst einen Ball. Kurze Aufgaben und freie Wege, keine Ausscheidung.','Richtungswechsel erst auf ein sichtbares Signal. Tempo an die Ballkontrolle anpassen.'],
 'Dribbling':['Mehr Platz oder breitere Dribbeltore geben. Erst ohne Zeitdruck lösen.','Einen aktiv verteidigenden Partner ergänzen, wenn der Aufbau dafür geeignet ist. Tore so stellen, dass mehrere Lösungen offen bleiben.'],
 'Passspiel':['Abstand kürzer wählen und mehr Kontakte erlauben. Nach dem Pass eine neue Anspielposition suchen.','Bei geeigneten Spielformen einen Verteidiger ergänzen. Nicht pauschal auf einen Kontakt begrenzen.'],
 'Torschuss':['Näher am Tor beginnen. Erst kontrolliert annehmen und dann schießen.','Zuspielwinkel wechseln. Nur schießen, wenn der Schussweg frei und das Tor sicher befestigt ist. Keine kreuzenden Rückwege.'],
 'Spielform':['Mit kleinen Teams und mehreren Feldern spielen. Wenn Tore fehlen, Dribbellinien verwenden.','Eine einzige Regel passend zum Lernziel ergänzen und nach einer kurzen Runde prüfen. Freies Spiel zum Vergleich.'],
 'Umschalten':['Nach Ballgewinn zunächst Zeit zum Orientieren geben. Ersatzball bereithalten.','Nach Ballverlust sofort zwischen Rückeroberung und Absichern entscheiden lassen. Nicht jede Aktion stoppen.'],
 'Verteidigen':['Kleineres Angriffsziel oder mehr Abstand für den Verteidiger. Zweikämpfe kontrolliert und ohne Grätschen.','Startpositionen wechseln und nach Ballgewinn ein Konterziel anbieten. Rollen regelmäßig tauschen.'],
 'Grundhaltung':['Langsame Bewegung und kurzer Zuspielweg. Erst bereit stehen, dann den Ball spielen.','Richtung des letzten Schritts variieren. Balltempo erst erhöhen, wenn die Grundstellung stabil ist.'],
 'Fangen':['Langsam und nah zuspielen, sichere Höhe wählen. Keine harten Schüsse auf unvorbereitete Kinder.','Zuspielrichtung ändern. Fangtechnik nur nach geschulter Anleitung und ohne Gegnerkontakt steigern.'],
 'Falltechnik':['Nur unter geschulter Anleitung auf weichem, geprüftem Boden. Bei Schmerz oder Unsicherheit abbrechen.','Keine Steigerung allein durch Tempo oder Höhe. Erst die sichere Bewegung vor Ort prüfen; Animation zeigt keine korrekte Landetechnik.'],
 'Spieleröffnung':['Kürzere Passwege und klare Anspieloptionen. Alle Kinder sollen Feldspieleraufgaben kennenlernen.','Schulterblick und Entscheidung zwischen zwei freien Mitspielern. Gegnerdruck erst hinzufügen, wenn der Aufbau das erlaubt.']
};
const coachDetail=renderDetail;renderDetail=function(){coachDetail();const e=exercise(detailId),tips=COACH_VARIANTS[e.tag];if(!tips)return;const box=document.createElement('section');box.className='coach-variants';box.innerHTML='<h3>Einfacher / anspruchsvoller</h3><p><strong>Einfacher:</strong> '+esc(tips[0])+'</p><p><strong>Anspruchsvoller:</strong> '+esc(tips[1])+'</p><p class="subtle">Redaktionelle Optionen, nur übernehmen, wenn sie zum konkreten Aufbau passen. Kurze Runden, Trinkpausen und Rollenwechsel vor Ort einplanen. Die Animation ist ein Aufbau-Schema, keine Technikvorführung.</p>';$('detailContent').querySelector('.detail-notes').append(box);const a=effective(e);$('detailContent').querySelector('.detail-facts').firstElementChild.textContent=a.minutes+' Min · deine Variante';$('detailContent').querySelector('.detail-facts').children[1].textContent=a.min+'-'+a.max+' Spieler / Gruppe';};
// Keep the important catalog warning accessible without blocking the home screen.
const catalogDetails=document.createElement('details');catalogDetails.id='catalogDetails';catalogDetails.innerHTML='<summary>Hinweis zu überarbeiteten Übungen</summary>';$('catalogNotice').before(catalogDetails);catalogDetails.append($('catalogNotice'));
