'use strict';
// V11: tap-to-place keyframes. Local SVG animation, no camera or video upload.
let editAnimation=null,editIndex=0,editActor='p0',editingId=null;
function validAnimation(a){return a&&a.version===1&&Array.isArray(a.frames)&&a.frames.length>=2&&a.frames.length<=20&&a.frames.every(f=>integer(f.seconds,1,15)&&text(f.caption,180)&&Array.isArray(f.points)&&f.points.length===4&&f.points.every(p=>Array.isArray(p)&&p.length===2&&p.every(Number.isFinite)&&p[0]>=25&&p[0]<=295&&p[1]>=25&&p[1]<=165));}
const baseFrame=()=>({seconds:3,caption:'Start: kurzer Pass.',points:[[65,95],[245,95],[160,50],[80,95]]});
const oldValidate=validate;validate=function(x){oldValidate(x);for(const e of x.custom)if(e.animation!==undefined&&!validAnimation(e.animation))throw Error('Ungültige Übungsanimation.');return x;};
const editorBox=document.createElement('details');editorBox.id='animationEditor';editorBox.innerHTML='<summary>Animation bauen (optional)</summary><p class="simple-tip">1. Spieler oder Ball wählen. 2. Auf das Feld tippen. 3. Nächsten Schritt anlegen. Die Animation verbindet die Positionen.</p><div id="editActors" class="editor-toolbar"><button type="button" data-edit-actor="0">Spieler 1</button><button type="button" data-edit-actor="1">Spieler 2</button><button type="button" data-edit-actor="2">Keeper K</button><button type="button" data-edit-actor="3">Ball</button></div><svg id="editPitch" class="editor-pitch" viewBox="0 0 320 190" role="img" aria-label="Aufbau: gewählten Spieler oder Ball durch Antippen platzieren"></svg><div class="row"><button type="button" id="framePrev">← Schritt</button><span id="frameLabel"></span><button type="button" id="frameNext">Schritt →</button></div><label>Schritt erklären<input id="frameCaption" maxlength="180"></label><label>Dauer (Sekunden)<input id="frameSeconds" type="number" min="1" max="15" value="3"></label><div class="editor-toolbar"><button id="frameAdd" type="button">+ Schritt</button><button id="frameDelete" type="button">Schritt löschen</button><button id="framePreview" type="button">Vorschau</button></div><p class="subtle">2-20 Schritte. Positionen schematisch, keine Technikdemo. Keeper lila. Vorschau stoppt bei weniger Bewegung.</p>';$('exSource').before(editorBox);
function editRead(){if(!editAnimation)return;const f=editAnimation.frames[editIndex];f.caption=$('frameCaption').value.trim()||'Schritt '+(editIndex+1);f.seconds=+$('frameSeconds').value;}
function editPaint(){const f=editAnimation.frames[editIndex];$('frameCaption').value=f.caption;$('frameSeconds').value=f.seconds;$('frameLabel').textContent=`${editIndex+1} / ${editAnimation.frames.length}`;$('framePrev').disabled=editIndex===0;$('frameNext').disabled=editIndex===editAnimation.frames.length-1;$('frameDelete').disabled=editAnimation.frames.length<=2;$('editPitch').innerHTML='<rect x="20" y="18" width="280" height="154" fill="none" stroke="#91bca5"/>'+f.points.map(([x,y],i)=>`<g><circle cx="${x}" cy="${y}" r="${i===3?5:11}" fill="${i===2?'#9154d9':i===3?'#fff':'#def5a2'}"/><text x="${x}" y="${y+4}">${i===3?'':i===2?'K':i+1}</text></g>`).join('');document.querySelectorAll('[data-edit-actor]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.editActor===String(editActor))));}
function editInit(e){editingId=e?.id||null;editIndex=0;editActor=0;editAnimation=e?.animation?structuredClone(e.animation):{version:1,frames:[baseFrame(),{seconds:3,caption:'Ball annehmen.',points:[[65,95],[245,95],[160,50],[230,95]]}]};editPaint();}
const editorNew=$('newExercise').onclick;$('newExercise').onclick=ev=>{editorNew(ev);editInit();};
$('editActors').onclick=ev=>{const b=ev.target.closest('[data-edit-actor]');if(b){editActor=+b.dataset.editActor;editPaint();}};
$('editPitch').onclick=ev=>{editRead();const r=ev.currentTarget.getBoundingClientRect();editAnimation.frames[editIndex].points[editActor]=[Math.round(Math.max(25,Math.min(295,(ev.clientX-r.left)/r.width*320))),Math.round(Math.max(25,Math.min(165,(ev.clientY-r.top)/r.height*190)))];editPaint();};
$('framePrev').onclick=()=>{editRead();editIndex--;editPaint();};$('frameNext').onclick=()=>{editRead();editIndex++;editPaint();};$('frameAdd').onclick=()=>{editRead();if(editAnimation.frames.length>=20)return notify('Maximal 20 Schritte.');editAnimation.frames.splice(editIndex+1,0,structuredClone(editAnimation.frames[editIndex]));editIndex++;editPaint();};$('frameDelete').onclick=()=>{if(editAnimation.frames.length<=2)return;editAnimation.frames.splice(editIndex,1);editIndex=Math.min(editIndex,editAnimation.frames.length-1);editPaint();};
$('framePreview').onclick=()=>{editRead();if(!validAnimation(editAnimation))return notify('Jeden Schritt mit 1-15 Sekunden und kurzer Erklärung ausfüllen.');if(reduced())return notify('Weniger Bewegung aktiv. Schritte manuell ansehen.');editIndex=0;editPaint();const f=editAnimation.frames;const total=f.reduce((s,x)=>s+x.seconds,0);$('editPitch').querySelectorAll('g').forEach((g,i)=>{const start=f[0].points[i];let t=0;const frames=f.map(x=>{const p=x.points[i],k={offset:t/total,transform:`translate(${p[0]-start[0]}px,${p[1]-start[1]}px)`};t+=x.seconds;return k;});frames.push({...frames.at(-1),offset:1});g.animate(frames,{duration:total*1000});});};
const submitCustom=$('exerciseForm').onsubmit;$('exerciseForm').onsubmit=ev=>{editRead();if(editorBox.open&&!validAnimation(editAnimation)){ev.preventDefault();$('formError').textContent='Animation prüfen: 2-20 Schritte, jeweils 1-15 Sekunden.';return;}const count=state.custom.length;submitCustom(ev);if(state.custom.length>count){const e=state.custom.at(-1);if(editorBox.open)e.animation=structuredClone(editAnimation);save();render();}};
const nativePitch=drillPitch;drillPitch=function(e,large=false,step=0){if(!e.custom||!validAnimation(e.animation))return nativePitch(e,large,step);const f=e.animation.frames[Math.min(step,e.animation.frames.length-1)],ps=f.points.slice(0,3),ball=f.points[3];return `<div class="pitch-scene scene-custom ${large?'pitch-large':''}" data-exercise="${esc(e.id)}" data-setup="customAnimation"><svg viewBox="0 0 320 190" role="img" aria-label="${esc(e.name)}: eigene schematische Animation"><g class="cam"><rect class="pitch-turf" x="1" y="1" width="318" height="188" rx="18"/><rect class="setup-boundary" x="20" y="18" width="280" height="154"/>${ps.map(([x,y],i)=>`<g data-actor="p${i}" data-x="${x}" data-y="${y}" data-label="${i===2?'K':i+1}" data-op="0"><g class="pitch-player ${i===2?'goalkeeper':''}"><circle cx="${x}" cy="${y}" r="10"/><text x="${x}" y="${y+3}">${i===2?'K':i+1}</text></g></g>`).join('')}<circle class="pitch-ball-static" cx="${ball[0]}" cy="${ball[1]}" r="5"/><circle class="actor-ball" data-actor="b0" data-x="${ball[0]}" data-y="${ball[1]}" cx="${ball[0]}" cy="${ball[1]}" r="5"/></g></svg><span class="scene-label">${esc(e.name)} · eigene Animation</span></div>`;};
const defaultSteps=stepsFor;stepsFor=function(e){return validAnimation(e.animation)?e.animation.frames.map(f=>f.caption):defaultSteps(e);};
const compileOriginal=SceneMotion.compile;SceneMotion.compile=function(scene,n,opts){if(scene.dataset.setup!=='customAnimation')return compileOriginal(scene,n,opts);const e=exercise(scene.dataset.exercise),f=e.animation.frames,anims=[],total=f.reduce((s,x)=>s+x.seconds*1000,0),starts=[];let t=0;f.forEach(x=>{starts.push(t);t+=x.seconds*1000;});scene.querySelectorAll('[data-actor]').forEach((g,i)=>{const actor=g.dataset.actor,ix=actor==='b0'?3:+actor.slice(1),x=+g.dataset.x,y=+g.dataset.y;const ks=f.map((v,k)=>({offset:starts[k]/total,transform:`translate(${v.points[ix][0]-x}px,${v.points[ix][1]-y}px)`}));ks.push({...ks.at(-1),offset:1});const a=g.animate(ks,{duration:total,fill:'both',easing:'linear'});a.pause();anims.push(a);});scene.classList.add('motion-on');return {total,anims,stepAt:ms=>Math.max(0,starts.findLastIndex(s=>s<=ms)),stepStart:i=>starts[i],get time(){return anims[0].currentTime||0;},get playing(){return anims[0].playState==='running';},get finished(){return this.time>=total-1;},play:r=>anims.forEach(a=>{a.playbackRate=r;a.play();}),pause:()=>anims.forEach(a=>a.pause()),seek:ms=>anims.forEach(a=>a.currentTime=ms),rate:r=>anims.forEach(a=>a.updatePlaybackRate(r)),moving:()=>[],destroy:()=>{anims.forEach(a=>a.cancel());scene.classList.remove('motion-on');}};};
render();
// V13: edit existing local drills and structured equipment, with lossless backup.
const extra=document.createElement('div');extra.innerHTML='<label>Bis Spieler pro Gruppe<input id="exMaxPeople" type="number" min="1" max="100" value="3"></label><label>Material mit Menge, eine Zeile pro Material<textarea id="exEquipment" rows="3" maxlength="2000" placeholder="4 Hütchen\n2 Bälle"></textarea></label><p class="subtle">Leer lassen: das einfache Materialfeld gilt als ein Materialpaket. Sonst z.B. 4 Hütchen und 2 Bälle in getrennten Zeilen.</p>';$('exSource').before(extra);
function parseEquipment(){if(!$('exEquipment').value.trim())return null;const rows=$('exEquipment').value.trim().split('\n').map(l=>{const m=l.trim().match(/^(\d+)\s+(.+)$/);if(!m||!integer(+m[1],1,100)||!text(m[2],100))throw Error('Material je Zeile: Menge 1-100, dann Name.');return [m[2],+m[1]];});if(rows.length>20)throw Error('Maximal 20 Materialien.');return rows;}
const edNew=$('newExercise').onclick;$('newExercise').onclick=ev=>{edNew(ev);$('exMaxPeople').value=$('exPeople').value;$('exEquipment').value='';editorBox.open=false;};
$('exPeople').addEventListener('input',()=>{if(!editingId)$('exMaxPeople').value=$('exPeople').value;});
function editCustom(e){$('detailDialog').close();$('exerciseForm').reset();$('formError').textContent='';editInit(e);for(const [id,v]of Object.entries({exName:e.name,exTag:e.tag,exType:e.type,exAge:e.ages[0],exDescription:e.description,exMaterial:e.equipment[0]?.[0]||'Bälle',exPeople:e.min,exMaxPeople:e.max,exMinutes:e.minutes,exSource:e.url,exEquipment:e.equipment.map(([n,c])=>c+' '+n).join('\n')}))$(id).value=v;editorBox.open=!!e.animation;$('exerciseDialog').showModal();}
const customDetail=renderDetail;renderDetail=function(){customDetail();const e=exercise(detailId);if(!e.custom)return;const b=document.createElement('button');b.id='editCustom';b.textContent='Eigene Übung bearbeiten';b.onclick=()=>editCustom(e);$('detailContent').querySelector('.detail-bottom').prepend(b);};
const editorSubmit=$('exerciseForm').onsubmit;$('exerciseForm').onsubmit=ev=>{let eq;const lo=+$('exPeople').value,hi=+$('exMaxPeople').value;try{if(!integer(hi,lo,100))throw Error('Bis-Spieler muss mindestens Von-Spieler sein.');eq=parseEquipment();editRead();if(editorBox.open&&!validAnimation(editAnimation))throw Error('Animation prüfen.');}catch(err){ev.preventDefault();$('formError').textContent=err.message;return;}if(editingId){ev.preventDefault();const old=exercise(editingId),next={...old,name:$('exName').value.trim(),tag:$('exTag').value,type:$('exType').value,ages:AGES.slice(AGES.indexOf($('exAge').value)),description:$('exDescription').value.trim(),min:lo,max:hi,minutes:+$('exMinutes').value,url:$('exSource').value.trim(),equipment:eq||[[$('exMaterial').value.trim(),1]]};if(editorBox.open)next.animation=structuredClone(editAnimation);else delete next.animation;try{validate({...state,custom:state.custom.map(e=>e.id===next.id?next:e)});state.custom=state.custom.map(e=>e.id===next.id?next:e);save();render();$('exerciseDialog').close();notify('Eigene Übung aktualisiert. Bestehende Blöcke bleiben erhalten.');}catch(err){$('formError').textContent=err.message;}return;}const before=state.custom.length;editorSubmit(ev);if(state.custom.length>before){const e=state.custom.at(-1);e.max=hi;if(eq)e.equipment=eq;save();render();}};
const backupValidate=validate;validate=function(x){backupValidate(x);if(x.variants!==undefined){if(!x.variants||typeof x.variants!=='object'||Array.isArray(x.variants)||Object.keys(x.variants).length>600)throw Error('Ungültige Varianten.');for(const [id,a] of Object.entries(x.variants))if(!text(id,100)||!a||!integer(a.min,1,100)||!integer(a.max,a.min,100)||!integer(a.minutes,1,120))throw Error('Ungültige Variante.');}return x;};
$('export').onclick=()=>download('trainr-backup.json',JSON.stringify({...state,variants:adapt},null,2),'application/json');
$('import').onchange=async ev=>{const file=ev.target.files[0];if(!file)return;try{if(file.size>2000000)throw Error('Backup zu groß (max. 2 MB).');const next=validate(JSON.parse(await file.text()));if(!confirm(`${next.plans.length} Pläne und ${next.custom.length} eigene Übungen wiederherstellen? Deine aktuellen Daten werden ersetzt.`))return;stopTimer();state=next;adapt=structuredClone(next.variants||{});localStorage.setItem(NEXT_KEY,JSON.stringify(adapt));timerIndex=0;resetTimer();save();render();if(!state.profile)setup();notify('Backup wiederhergestellt.');}catch(err){notify('Import abgelehnt: '+err.message);}finally{ev.target.value='';}};
$('editPitch').setAttribute('tabindex','0');$('editPitch').setAttribute('aria-label','Gewählten Spieler oder Ball platzieren: auf das Feld tippen oder mit Pfeiltasten in 5er-Schritten verschieben.');$('editPitch').addEventListener('keydown',ev=>{const changes={ArrowLeft:[-5,0],ArrowRight:[5,0],ArrowUp:[0,-5],ArrowDown:[0,5]},d=changes[ev.key];if(!d)return;ev.preventDefault();editRead();const p=editAnimation.frames[editIndex].points[editActor];p[0]=Math.max(25,Math.min(295,p[0]+d[0]));p[1]=Math.max(25,Math.min(165,p[1]+d[1]));editPaint();});
const editorQuiet=()=>{$('editPitch').getAnimations({subtree:true}).forEach(a=>a.cancel());};$('exerciseDialog').addEventListener('close',editorQuiet);$('motionSetting').addEventListener('change',()=>{if(reduced())editorQuiet();});matchMedia('(prefers-reduced-motion: reduce)').addEventListener('change',()=>{if(reduced())editorQuiet();});
