const {chromium}=require('@playwright/test'),assert=require('node:assert/strict'),fs=require('node:fs'),server=require('./serve.cjs');
(async()=>{await new Promise(r=>server.listen(8766,'127.0.0.1',r));const browser=await chromium.launch({executablePath:'/usr/bin/google-chrome',args:['--no-sandbox']});try{const ctx=await browser.newContext({reducedMotion:'reduce',viewport:{width:390,height:844}}),page=await ctx.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://localhost:8766');await page.selectOption('#coachAge','E-Jugend');await page.click('#setupNext');await page.click('#setupNext');await page.click('#setupNext');await page.click('[data-view=planner]');
assert.equal(await page.evaluate(()=>SEED.length),100);assert.equal(await page.evaluate(()=>new Set(SEED.map(e=>e.id)).size),100);
await page.selectOption('#buildFocus','Passspiel');await page.fill('#buildMinutes','60');await page.fill('#buildPeople','12');await page.click('#buildPreview');assert.equal(await page.locator('.proposal-list li').count(),4);assert.equal(await page.evaluate(()=>proposed.blocks.reduce((n,b)=>n+b.minutes,0)),60);assert.equal(await page.evaluate(()=>proposed.blocks.every(b=>exercise(b.exerciseId).ages.includes('E-Jugend')&&candidateGroups(exercise(b.exerciseId),12))),true);
await page.screenshot({path:'/downloads/trainr-v5-planner-mobile.png',fullPage:true});const old=await page.evaluate(()=>state.plans[0].id);await page.click('#buildApply');assert.equal(await page.evaluate(()=>state.plans.length),2);assert.equal(await page.evaluate(()=>state.plans[0].id),old);assert.equal(await page.locator('.block').count(),4);
await page.locator('.export-drawer').evaluate(d=>d.open=true);await page.click('#exportPdf');assert.equal(await page.locator('#exportDialog').isVisible(),true);const pdf=page.waitForEvent('download');await page.click('#exportDownload');await (await pdf).saveAs('/downloads/TRAINR-v5-example.pdf');await page.screenshot({path:'/downloads/trainr-v5-export-mobile.png',fullPage:true});await page.click('#exportClose');await page.click('#exportImage');const png=page.waitForEvent('download');await page.click('#exportDownload');await(await png).saveAs('/downloads/TRAINR-v5-example.png');await page.click('#exportClose');
await page.reload();assert.equal(await page.evaluate(()=>plan().age),'E-Jugend');await page.click('[data-view=planner]');await page.fill('#buildMinutes','19');await page.click('#buildPreview');assert.match(await page.locator('#buildResult').innerText(),/20-120/);await page.fill('#buildMinutes','60');await page.selectOption('#buildAge','Bambini');await page.click('#buildPreview');assert.equal(await page.evaluate(()=>proposed.blocks.every(b=>exercise(b.exerciseId).ages.includes('Bambini'))),true);
assert.equal(await page.evaluate(()=>{try{makeProposal({age:'Bambini',people:2,minutes:20,focus:'Alle',type:'keeper'});return false}catch{return true}}),true);
const keeper=await page.evaluate(()=>makeProposal({age:'E-Jugend',people:2,minutes:20,focus:'Fangen',type:'keeper'}));assert.equal(keeper.blocks.length,3);assert.equal(keeper.blocks.reduce((n,b)=>n+b.minutes,0),20);
// All returned proposals obey age/type/group and exact budget. Unsupported combos must explain why.
const matrix=await page.evaluate(()=>{let pass=0,blocked=0;for(const age of AGES)for(const type of ['field','keeper','both'])for(const people of [1,2,3,4,7,11,12,24,40])for(const minutes of [20,45,60,120]){try{const p=makeProposal({age,type,people,minutes,focus:'Alle'});if(p.blocks.reduce((s,b)=>s+b.minutes,0)!==minutes||p.blocks.some(b=>!exercise(b.exerciseId).ages.includes(age)||!candidateGroups(exercise(b.exerciseId),people)||exercise(b.exerciseId).tag==='Falltechnik'))throw Error('VIOLATION');pass++;}catch(e){if(e.message==='VIOLATION')throw e;blocked++;}}return{pass,blocked};});console.log('Proposal matrix',matrix);
await page.setViewportSize({width:1280,height:900});await page.selectOption('#buildAge','E-Jugend');await page.click('#buildPreview');await page.screenshot({path:'/downloads/trainr-v5-planner-desktop.png',fullPage:true});await page.click('[data-view=library]');await page.screenshot({path:'/downloads/trainr-v5-library-desktop.png',fullPage:true});
for(const width of [360,390,768,1280]){await page.setViewportSize({width,height:844});await page.click('[data-view=planner]');assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);}
await page.waitForFunction(()=>navigator.serviceWorker.controller);await ctx.setOffline(true);await page.reload();assert.equal(await page.evaluate(()=>SEED.length),100);assert.equal(await page.locator('#buildPreview').count(),1);await page.click('[data-view=planner]');await page.locator('.export-drawer').evaluate(d=>d.open=true);await page.click('#exportPdf');assert.equal(await page.locator('#exportDialog').isVisible(),true);assert.deepEqual(errors,[]);console.log('PASS V5: 100 unique drills, safe matrix, preview/new-plan/persistence, exact times, real PDF/PNG downloads, invalid inputs, keeper/Bambini boundaries, responsive, offline exports.');}finally{await browser.close();server.close();}})().catch(e=>{console.error(e);process.exitCode=1});
