const {chromium}=require('@playwright/test'),assert=require('node:assert/strict'),server=require('./serve.cjs');
(async()=>{await new Promise(r=>server.listen(8891,r));const browser=await chromium.launch({executablePath:'/usr/bin/google-chrome',args:['--no-sandbox']});try{
 const c=await browser.newContext({viewport:{width:390,height:844},reducedMotion:'no-preference'}),p=await c.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto('http://localhost:8891');for(let i=0;i<3;i++)await p.click('#setupNext');await p.click('#easyCreate');await p.click('#homeStart');await p.waitForFunction(()=>liveDemoTL?.playing);assert.equal(await p.evaluate(()=>$('liveDemoPitch').firstElementChild.dataset.exercise),await p.evaluate(()=>plan().blocks[timerIndex].exerciseId));
 // The same scene survives 200ms clock paints and advances independently.
 await p.evaluate(()=>window.savedTL=liveDemoTL);await p.waitForTimeout(700);assert(await p.evaluate(()=>savedTL===liveDemoTL&&liveDemoTL.time>700));
 await p.waitForTimeout(1100);await p.evaluate(()=>$('status').classList.add('hidden'));await p.screenshot({path:'/downloads/trainr-v19-timer-390.png',fullPage:false});
 await p.click('#startTimer');await p.waitForFunction(()=>!liveDemoTL.playing);const paused=await p.evaluate(()=>liveDemoTL.time);await p.waitForTimeout(250);assert(Math.abs(await p.evaluate(()=>liveDemoTL.time)-paused)<30);await p.click('#startTimer');await p.waitForFunction(()=>liveDemoTL.playing);
 // Optional animation pause never changes the real deadline.
 const deadline0=await p.evaluate(()=>deadline);await p.click('#liveDemoToggle');assert.equal(await p.evaluate(()=>deadline),deadline0);assert.equal(await p.evaluate(()=>liveDemoTL.playing),false);await p.click('#liveDemoToggle');assert(await p.evaluate(()=>liveDemoTL.playing));
 // Loop at completion, then reset and change blocks without the old scene surviving.
 await p.evaluate(()=>liveDemoTL.seek(liveDemoTL.total-30));await p.waitForFunction(()=>liveDemoTL.time<1000);await p.click('#resetTimer');assert.equal(await p.evaluate(()=>!!deadline),false);assert((await p.evaluate(()=>liveDemoTL.time))<100);assert.equal(await p.evaluate(()=>liveDemoStep),0);await p.click('#nextBlock');assert.equal(await p.evaluate(()=>timerIndex),1);assert.equal(await p.evaluate(()=>savedTL.anims[0].playState),'idle');assert.equal(await p.evaluate(()=>$('liveDemoPitch').firstElementChild.dataset.exercise),await p.evaluate(()=>plan().blocks[1].exerciseId));await p.click('#startTimer');
 // Other screens and modal pause the visual only; clock keeps its deadline.
 const runningDeadline=await p.evaluate(()=>deadline);await p.click('[data-view=home]');assert.equal(await p.evaluate(()=>liveDemoTL.playing),false);assert.equal(await p.evaluate(()=>deadline),runningDeadline);await p.click('[data-view=live]');await p.waitForFunction(()=>liveDemoTL.playing);await p.click('#liveSource');await p.waitForFunction(()=>!liveDemoTL.playing);assert.equal(await p.evaluate(()=>deadline),runningDeadline);await p.evaluate(()=>$('detailDialog').close());await p.waitForFunction(()=>liveDemoTL.playing);
 // System reduced motion has priority. Steps remain manually accessible.
 await p.emulateMedia({reducedMotion:'reduce'});await p.waitForFunction(()=>liveDemoTL===null);assert(await p.locator('#liveDemoToggle').isHidden());await p.click('#liveDemoNext');assert.equal(await p.evaluate(()=>liveDemoStep),1);assert.equal(await p.evaluate(()=>deadline),runningDeadline);await p.click('#liveDemoPrev');assert.equal(await p.evaluate(()=>liveDemoStep),0);await p.emulateMedia({reducedMotion:'no-preference'});await p.waitForFunction(()=>liveDemoTL!==null);await p.click('#liveDemoToggle');await p.waitForFunction(()=>liveDemoTL.playing);
 // App motion switch also works, without any timer mutation.
 await p.evaluate(()=>{$('motionSetting').checked=false;$('motionSetting').dispatchEvent(new Event('change'));});assert.equal(await p.evaluate(()=>liveDemoTL),null);assert.equal(await p.evaluate(()=>deadline),runningDeadline);await p.evaluate(()=>{$('motionSetting').checked=true;$('motionSetting').dispatchEvent(new Event('change'));});await p.waitForFunction(()=>liveDemoTL.playing);
 // Own keyframe animation, then no-animation custom fallback, and empty plan.
 await p.evaluate(()=>{stopTimer();const e={...structuredClone(SEED[0]),id:'test-v19-custom',custom:true,name:'Eigene Passübung',animation:{version:1,frames:[{seconds:1,caption:'Zuspiel',points:[[65,95],[245,95],[160,50],[80,95]]},{seconds:1,caption:'Annehmen',points:[[95,95],[225,95],[160,60],[220,95]]}]}};state.custom.push(e);plan().blocks=[{id:'custom-block',exerciseId:e.id,minutes:1}];timerIndex=0;resetTimer();render();});await p.click('#startTimer');await p.waitForFunction(()=>liveDemoTL?.playing);assert.equal(await p.evaluate(()=>$('liveDemoPitch').firstElementChild.dataset.setup),'customAnimation');assert.equal(await p.locator('#liveDemoPitch .actor-ball').evaluate(el=>getComputedStyle(el).display),'block');await p.evaluate(()=>{stopTimer();delete state.custom.at(-1).animation;render();});assert.equal(await p.evaluate(()=>liveDemoTL),null);assert.equal(await p.locator('#liveDemoStatus').textContent(),'Aufbau & Schritte');await p.click('#liveDemoNext');assert.equal(await p.evaluate(()=>liveDemoStep),1);
 // Keeper graphic and responsive pixels.
 await p.evaluate(()=>{plan().blocks=[{id:'keeper-block',exerciseId:'catch',minutes:4},{id:'keeper-next',exerciseId:'ready',minutes:3}];timerIndex=0;resetTimer();render();});await p.click('#startTimer');await p.waitForFunction(()=>liveDemoTL.playing);assert(await p.locator('#liveDemoPitch .goalkeeper').count());for(const w of [360,390,768,1280]){await p.setViewportSize({width:w,height:844});await p.evaluate(()=>scrollTo(0,0));await p.waitForTimeout(500);await p.evaluate(()=>$('status').classList.add('hidden'));assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await p.screenshot({path:`/downloads/trainr-v19-keeper-${w}.png`});}
 // Countdown completion stops looping and leaves final schematic visible.
 await p.evaluate(()=>{deadline=Date.now()-1;updateClock();});assert.equal(await p.evaluate(()=>remaining),0);assert.equal(await p.evaluate(()=>liveDemoTL.playing),false);
 await p.evaluate(()=>{plan().blocks=[];resetTimer();render();});assert(await p.locator('#liveDemo').isHidden());assert.equal(await p.evaluate(()=>liveDemoTL),null);assert.deepEqual(errors,[]);
 console.log('PASS V19 animation follows timer; stable timeline; loop; independent visual pause; timer pause/resume/reset/end; next block; view/modal pause; system/app reduced motion; manual steps; own-animation/static fallback; keeper; empty plan; 360/390/768/1280 widths; no JS errors.');
 }finally{await browser.close();server.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
