'use strict';
// Optional per-exercise variants. Seed defaults and existing backups stay unchanged.
const NEXT_KEY='trainr-adapt-v1';let adapt={};try{adapt=JSON.parse(localStorage.getItem(NEXT_KEY))||{};}catch{}
function effective(e){const a=adapt[e.id];return a&&integer(a.min,1,100)&&integer(a.max,a.min,100)&&integer(a.minutes,1,120)?{...e,min:a.min,max:a.max,minutes:a.minutes}:e;}
const nextFit=fit;fit=function(e,n){return nextFit(effective(e),n);};
function variantLabel(e){const a=effective(e);return `${a.min===a.max?a.min:a.min+'-'+a.max} Spieler / Gruppe · anpassbar`;}
const nextCards=renderCards;renderCards=function(){nextCards();document.querySelectorAll('#cards .card').forEach(c=>{const e=exercise(c.dataset.drag);c.querySelector('.meta span:nth-child(2)').textContent=variantLabel(e);});};
const nextDetail=renderDetail;renderDetail=function(){nextDetail();const e=exercise(detailId),a=effective(e);const b=document.createElement('section');b.className='adapt-box';b.innerHTML=`<h3>Deine Variante</h3><p class="simple-tip">Der Aufbau ist ein Vorschlag, kein festes Format. Mehr Gruppen, kürzere Runden oder größere Abstände sind möglich. Können, Platz und Helfer prüfen.</p><div class="row"><label>Von Spielern<input id="adaptMin" type="number" min="1" max="100" value="${a.min}"></label><label>Bis Spielern<input id="adaptMax" type="number" min="1" max="100" value="${a.max}"></label><label>Minuten<input id="adaptMinutes" type="number" min="1" max="120" value="${a.minutes}"></label></div><div class="row"><button id="saveAdapt">Variante merken</button><button id="resetAdapt">Original</button></div><p class="subtle">Nur auf diesem Gerät. Schon geplante Blockminuten bleiben erhalten. Materialbedarf basiert weiter auf dem Originalaufbau.</p>`;$('detailContent').querySelector('.detail-notes').prepend(b);$('saveAdapt').onclick=()=>{const a={min:+$('adaptMin').value,max:+$('adaptMax').value,minutes:+$('adaptMinutes').value};if(!integer(a.min,1,100)||!integer(a.max,a.min,100)||!integer(a.minutes,1,120))return notify('Gültigen Bereich und 1-120 Minuten wählen.');adapt[e.id]=a;try{localStorage.setItem(NEXT_KEY,JSON.stringify(adapt));}catch{return notify('Variante konnte nicht gespeichert werden.');}render();renderDetail();notify('Deine Variante gespeichert.');};$('resetAdapt').onclick=()=>{delete adapt[e.id];try{localStorage.setItem(NEXT_KEY,JSON.stringify(adapt));}catch{}render();renderDetail();};};
const nextAdd=add;add=function(id){nextAdd(id);const b=plan().blocks.at(-1),e=exercise(id);if(b&&b.exerciseId===id){b.minutes=effective(e).minutes;save();render();}};
render();
