'use strict';
// Optional per-exercise variants. Seed defaults and existing backups stay unchanged.
const NEXT_KEY='trainr-adapt-v1';let adapt={};try{adapt=JSON.parse(localStorage.getItem(NEXT_KEY))||{};}catch{}
function effective(e){const a=adapt[e.id];return a&&integer(a.min,1,100)&&integer(a.max,a.min,100)&&integer(a.minutes,1,120)?{...e,min:a.min,max:a.max,minutes:a.minutes}:e;}
const nextFit=fit;fit=function(e,n){return nextFit(effective(e),n);};
function variantLabel(e){const a=effective(e);return `${a.min===a.max?a.min:a.min+'-'+a.max} Spieler / Gruppe · anpassbar`;}
const nextCards=renderCards;renderCards=function(){nextCards();document.querySelectorAll('#cards .card').forEach(c=>{const e=exercise(c.dataset.drag);c.querySelector('.meta span:nth-child(2)').textContent=variantLabel(e);});};
const nextDetail=renderDetail;renderDetail=function(){nextDetail();const e=exercise(detailId),a=effective(e);const b=document.createElement('section');b.className='adapt-box';b.innerHTML=`<h3>Deine Variante</h3><p class="simple-tip">Der Aufbau ist ein Vorschlag, kein festes Format. Mehr Gruppen, kürzere Runden oder größere Abstände sind möglich. Können, Platz und Helfer prüfen.</p><div class="row"><label>Von Spielern<input id="adaptMin" type="number" min="1" max="100" value="${a.min}"></label><label>Bis Spielern<input id="adaptMax" type="number" min="1" max="100" value="${a.max}"></label><label>Minuten<input id="adaptMinutes" type="number" min="1" max="120" value="${a.minutes}"></label></div><div class="row"><button id="saveAdapt">Variante merken</button><button id="resetAdapt">Original</button></div><p class="subtle">Nur auf diesem Gerät. Schon geplante Blockminuten bleiben erhalten. Materialbedarf basiert weiter auf dem Originalaufbau.</p>`;$('detailContent').querySelector('.detail-notes').prepend(b);$('saveAdapt').onclick=()=>{const a={min:+$('adaptMin').value,max:+$('adaptMax').value,minutes:+$('adaptMinutes').value};if(!integer(a.min,1,100)||!integer(a.max,a.min,100)||!integer(a.minutes,1,120))return notify('Gültigen Bereich und 1-120 Minuten wählen.');adapt[e.id]=a;try{localStorage.setItem(NEXT_KEY,JSON.stringify(adapt));}catch{return notify('Variante konnte nicht gespeichert werden.');}render();renderDetail();notify('Deine Variante gespeichert.');};$('resetAdapt').onclick=()=>{delete adapt[e.id];try{localStorage.setItem(NEXT_KEY,JSON.stringify(adapt));}catch{}render();renderDetail();};};
const nextAdd=add;add=function(id){nextAdd(id);const b=plan().blocks.at(-1),e=exercise(id);if(b&&b.exerciseId===id){b.minutes=effective(e).minutes;save();render();}};
render();
// V10: equipment is a visual, filterable catalog, never a hidden inventory check.
const MATERIALS=[['ball','⚽','Bälle',/ball|bäll/i],['cone','▲','Hütchen',/hütchen|kegel/i],['goal','▣','Tore',/tor/i],['bib','▰','Leibchen',/leibchen/i],['ground','▤','Weicher Boden',/boden|matte/i],['other','◇','Weiteres',/.*/]];
function materialType(name){return MATERIALS.find(m=>m[0]!=='other'&&m[3].test(name))||MATERIALS.at(-1);}
function materialPills(items){return items.map(([n,c])=>`<span class="material-chip"><span aria-hidden="true">${materialType(n)[1]}</span>${c} ${esc(n)}</span>`).join('');}
const ml=document.createElement('label');ml.htmlFor='materialFilter';ml.textContent='Material';const mf=document.createElement('select');mf.id='materialFilter';mf.innerHTML='<option value="all">Jedes Material</option>'+MATERIALS.map(m=>`<option value="${m[0]}">${m[1]} ${m[2]}</option>`).join('');$('typeFilter').parentElement.append(ml,mf);mf.onchange=()=>renderCards();
const materialCards=renderCards;renderCards=function(){materialCards();let count=0;document.querySelectorAll('#cards .card').forEach(c=>{const e=exercise(c.dataset.drag);if(mf.value!=='all'&&!e.equipment.some(([n])=>materialType(n)[0]===mf.value)){c.remove();return;}count++;const para=[...c.querySelectorAll(':scope > p')].find(p=>p.textContent.startsWith('Material je Gruppe'));if(para)para.innerHTML='<strong>Material je Gruppe:</strong><br>'+materialPills(e.equipment);});$('drillCount').textContent=count+' sichtbar';if(!count&&!$('cards').textContent.trim())$('cards').innerHTML='<p class="empty">Keine Übung mit diesem Material. Materialfilter zurücksetzen.</p>';};
const materialDetail=renderDetail;renderDetail=function(){materialDetail();const e=exercise(detailId),p=$('detailContent').querySelector('.equipment-pills');if(p)p.innerHTML=materialPills(e.equipment);};
const matRender=render;render=function(){matRender();const eq=requirements();$('equipmentSummary').querySelector('p').innerHTML=materialPills(Object.entries(eq))||'Noch keine Übungen.';};
render();
// V12: one clear path, while keeping the advanced controls available.
const quick=document.createElement('div');quick.className='quick-row';quick.innerHTML='<button id="quickBrowse">1 · Übung wählen</button><button id="quickPlan">2 · Plan prüfen</button><button id="quickTrain">3 · Training starten</button>';$('homeStats').after(quick);$('quickBrowse').onclick=()=>view('library');$('quickPlan').onclick=()=>view('planner');$('quickTrain').onclick=()=>view('live');
const resetFilters=document.createElement('button');resetFilters.id='resetFilters';resetFilters.textContent='Filter zurücksetzen';resetFilters.type='button';$('search').after(resetFilters);resetFilters.onclick=()=>{$('search').value='';$('filter').value='Alle Schwerpunkte';$('typeFilter').value='all';$('ageFilter').value='Alle Altersklassen';mf.value='all';setFavoriteFilter(false);renderCards();notify('Alle Übungen sichtbar. Altersklasse selbst prüfen.');};
const activeFilters=document.createElement('p');activeFilters.id='activeFilters';activeFilters.className='simple-tip';$('search').after(activeFilters);
const simpleCards=renderCards;renderCards=function(){simpleCards();const parts=[$('filter').value!=='Alle Schwerpunkte'?$('filter').value:'',$('typeFilter').value==='profile'?'Mein Profil':$('typeFilter').value==='all'?'':LABELS[$('typeFilter').value],$('ageFilter').value==='Alle Altersklassen'?'':$('ageFilter').value,mf.value==='all'?'':MATERIALS.find(m=>m[0]===mf.value)[2],favoritesOnly?'Merkliste':''].filter(Boolean);activeFilters.textContent=parts.length?'Aktive Filter: '+parts.join(' · '):'Alle Übungen. Öffnen, ansehen, in den Plan übernehmen.';};
const quickRender=render;render=function(){quickRender();$('quickTrain').disabled=!plan().blocks.length;};
const pt=document.createElement('p');pt.className='simple-tip';pt.textContent='Minuten direkt ändern. Pfeile ordnen die Übungen. Weitere Optionen stecken unter Planeinstellungen und Export.';$('blocks').before(pt);
render();
// V14: material checklist and keyboard/touch navigation for the local editor.
const checklist=document.createElement('details');checklist.id='materialChecklist';checklist.innerHTML='<summary>Material abhaken</summary><div id="checkItems"></div><p class="subtle">Checkliste für jetzt, kein gespeichertes Inventar. Mengen nach jeder Planänderung neu prüfen.</p>';$('equipmentSummary').after(checklist);
const checkRender=render;render=function(){checkRender();$('checkItems').innerHTML=Object.entries(requirements()).map(([n,c],i)=>`<label class="toggle-row"><input type="checkbox" style="width:auto"> ${materialType(n)[1]} ${c} ${esc(n)}</label>`).join('')||'Noch keine Übungen.';};
const profileSafety=document.createElement('p');profileSafety.className='simple-tip';profileSafety.textContent='Backup sichert jetzt auch eigene Animationen und Varianten. Browserdaten nicht löschen. Ein Backup enthält keine Merkliste oder Anzeigeeinstellungen.';$('export').before(profileSafety);
render();
