'use strict';
// Motion is presentation only. No plan, storage schema or training logic changes.
const motionSelector='.panel,.training-ticket,.dynamic-card,.block,.timeline-row,.notice,.home-action,.welcome,.section-heading,#liveCoaching,.detail-heading,.detail-notes>section,.preview-caption,.equipment-pills>span,.choice,.planner-assistant';
const motionNodes=new Set(),motionSeen=new WeakSet(),motionEffects=new Set();
let motionFrame=0,motionDragging=false,tiltTarget=null,tiltPoint=null;
const motionBackdrop=document.createElement('div');motionBackdrop.className='motion-atmosphere';motionBackdrop.setAttribute('aria-hidden','true');motionBackdrop.innerHTML='<i></i><i></i>';document.body.prepend(motionBackdrop);
function motionAllowed(){return !reduced()&&!document.hidden&&!motionDragging;}
function motionAnimate(node,frames,options){if(!motionAllowed()||!node.animate)return;const effect=node.animate(frames,options);motionEffects.add(effect);effect.finished.catch(()=>{}).finally(()=>motionEffects.delete(effect));return effect;}
function motionReveal(node,index=0){if(motionSeen.has(node)||!motionAllowed())return;motionSeen.add(node);motionAnimate(node,[{opacity:.25,transform:'translateY(26px) scale(.975)'},{opacity:1,transform:'translateY(0) scale(1)'}],{duration:560,delay:Math.min(index*45,270),easing:'cubic-bezier(.16,1,.3,1)'});}
const motionObserver=new IntersectionObserver(entries=>{let i=0;for(const entry of entries){entry.target.classList.toggle('motion-visible',entry.isIntersecting);if(entry.isIntersecting)motionReveal(entry.target,i++);}motionBudget();},{threshold:0.08});
function motionBudget(){let floating=0;for(const node of motionNodes){if(!node.isConnected){motionObserver.unobserve(node);motionNodes.delete(node);continue;}const on=motionAllowed()&&node.classList.contains('motion-visible')&&node.getClientRects().length&&floating<10&&(node.matches('.dynamic-card,.training-ticket,.block,.timeline-row,.panel:not(#onboarding)'));  node.classList.toggle('motion-float',!!on);if(on)floating++;}}
function motionScan(){motionFrame=0;let i=0;document.querySelectorAll(motionSelector).forEach(node=>{if(motionNodes.has(node))return;motionNodes.add(node);node.style.setProperty('--motion-phase',(-i++*.67)+'s');motionObserver.observe(node);});motionBudget();}
function motionQueue(){if(!motionFrame)motionFrame=requestAnimationFrame(motionScan);}
new MutationObserver(motionQueue).observe(document.querySelector('main'),{childList:true,subtree:true});
new MutationObserver(motionQueue).observe($('detailDialog'),{childList:true,subtree:true});
function motionResetTilt(){if(tiltTarget){tiltTarget.style.removeProperty('--tilt-x');tiltTarget.style.removeProperty('--tilt-y');tiltTarget.style.removeProperty('--lift');tiltTarget=null;}tiltPoint=null;}
let tiltFrame=0;
document.addEventListener('pointermove',ev=>{if(ev.pointerType!=='mouse'||!matchMedia('(hover: hover) and (pointer: fine)').matches||!motionAllowed())return;const target=ev.target.closest('.dynamic-card,.training-ticket,.block');if(target!==tiltTarget){motionResetTilt();tiltTarget=target;}if(!target)return;tiltPoint={x:ev.clientX,y:ev.clientY};if(!tiltFrame)tiltFrame=requestAnimationFrame(()=>{tiltFrame=0;if(!tiltTarget||!tiltPoint)return;const r=tiltTarget.getBoundingClientRect();tiltTarget.style.setProperty('--tilt-x',((tiltPoint.y-r.top)/r.height-.5)*-3+'deg');tiltTarget.style.setProperty('--tilt-y',((tiltPoint.x-r.left)/r.width-.5)*3+'deg');tiltTarget.style.setProperty('--lift','-3px');});},{passive:true});
document.addEventListener('pointerout',ev=>{if(tiltTarget&&!tiltTarget.contains(ev.relatedTarget))motionResetTilt();});
document.addEventListener('pointerdown',ev=>{const target=ev.target.closest('button,summary,.dynamic-card');if(target&&!target.disabled)motionAnimate(target,[{scale:'1'},{scale:'.96'},{scale:'1'}],{duration:260,easing:'cubic-bezier(.2,.8,.2,1)'});},{passive:true});
function motionSync(){document.body.classList.toggle('motion-active',motionAllowed());if(!motionAllowed()){motionEffects.forEach(a=>a.cancel());motionEffects.clear();motionResetTilt();}motionBudget();}
$('motionSetting').addEventListener('change',motionSync);matchMedia('(prefers-reduced-motion: reduce)').addEventListener('change',motionSync);document.addEventListener('visibilitychange',motionSync);
document.addEventListener('dragstart',()=>{motionDragging=true;motionSync();},true);document.addEventListener('dragend',()=>{motionDragging=false;motionSync();},true);document.addEventListener('drop',()=>{motionDragging=false;motionSync();},true);
const v7View=view;view=function(name,opts){v7View(name,reduced()?{...opts,scroll:false}:opts);if(reduced()&&opts?.scroll!==false)window.scrollTo({top:0,behavior:'instant'});motionScan();const id={home:'homeView',library:'library',planner:'planner',live:'liveView',info:'info'}[name];if(id&&motionAllowed())document.querySelectorAll('#'+id+'>.welcome,#'+id+'>.home-action,#'+id+'>.row,#'+id+'>.tools,#'+id+'>.library-intro').forEach((n,i)=>motionAnimate(n,[{opacity:0,transform:'translateY(18px)'},{opacity:1,transform:'translateY(0)'}],{duration:480,delay:i*45,easing:'cubic-bezier(.16,1,.3,1)'}));};
const v7Detail=renderDetail;renderDetail=function(){v7Detail();motionScan();document.querySelectorAll('.detail-heading,.detail-notes>section').forEach((node,i)=>motionAnimate(node,[{opacity:.3,transform:'translateY(16px)'},{opacity:1,transform:'translateY(0)'}],{duration:450,delay:i*35,easing:'ease-out'}));};
// A small scroll-driven offset, updated once per frame only while scrolling.
let scrollMotionFrame=0;window.addEventListener('scroll',()=>{if(!motionAllowed()||scrollMotionFrame)return;scrollMotionFrame=requestAnimationFrame(()=>{scrollMotionFrame=0;motionBackdrop.style.setProperty('--scroll-drift',Math.min(scrollY*.035,35)+'px');});},{passive:true});
motionScan();motionSync();
