'use strict';
// Presentation preferences are separate from plan backups. No network resources.
const UI_KEY='trainr-ui-v4';
let uiPrefs={favorites:[],motion:true,haptics:false};
try {const p=JSON.parse(localStorage.getItem(UI_KEY));if(p&&Array.isArray(p.favorites))uiPrefs={favorites:p.favorites.filter(x=>typeof x==='string'),motion:p.motion!==false,haptics:p.haptics===true};}catch{}
const reduced=()=>!uiPrefs.motion||matchMedia('(prefers-reduced-motion: reduce)').matches;
function saveUI(){try{localStorage.setItem(UI_KEY,JSON.stringify(uiPrefs));}catch{notify('Darstellung konnte nicht gespeichert werden.');}}
function applyUI(){document.body.classList.toggle('quiet-motion',!uiPrefs.motion);}
applyUI();
const intro=document.createElement('div');intro.className='library-intro';intro.innerHTML='<p>Eine Idee. Ein Blick. Ab auf den Platz.</p><div class="library-chips"><button id="allDrills" class="active" aria-pressed="true">Alle Übungen</button><button id="favoriteDrills" aria-pressed="false">♡ Merkliste</button><span id="drillCount" role="status"></span></div>';$('profileSummary').before(intro);
let favoritesOnly=false,detailId=null,detailStep=0,detailLoop=null,detailPlaying=false,detailReturnFocus=null;
const stepsFor=e=>e.description.match(/[^.!?]+[.!?]+|[^.!?]+$/g)?.map(s=>s.trim()).filter(Boolean)||[e.description];
function sceneFor(e){if(e.custom)return 'custom';if(e.type==='keeper')return 'keeper';if(['Dribbling','Aufwärmen'].includes(e.tag))return 'dribble';if(e.tag==='Passspiel'||e.tag==='Spieleröffnung')return 'pass';if(e.tag==='Torschuss')return 'shot';return 'game';}
function pitch(e,large=false){return drillPitch(e,large);}
const v4Cards=renderCards;renderCards=function(){v4Cards();const cards=[...$('cards').querySelectorAll('.card')];let visible=0;for(const card of cards){const e=exercise(card.dataset.drag),fav=uiPrefs.favorites.includes(e.id);if(favoritesOnly&&!fav){card.remove();continue;}visible++;card.classList.add('dynamic-card');card.querySelector('.drill-sketch')?.remove();card.querySelector('h3').after(document.createRange().createContextualFragment(pitch(e)));card.querySelector('[data-detail]').textContent='Übung ansehen ↗';card.querySelector('[data-detail]').className='detail-link';card.querySelector('[data-detail]').setAttribute('aria-label',e.name+' ansehen');const star=document.createElement('button');star.className='favorite-button';star.dataset.favorite=e.id;star.textContent=fav?'♥':'♡';star.setAttribute('aria-label',e.name+(fav?' aus Merkliste entfernen':' merken'));star.setAttribute('aria-pressed',String(fav));card.prepend(star);const note=document.createElement('p');note.className='sketch-note';note.textContent='Illustrative Skizze · keine exakten Laufwege';card.querySelector('.pitch-scene').after(note);}
 $('drillCount').textContent=visible+' sichtbar';if(!visible&&favoritesOnly)$('cards').innerHTML='<div class="empty"><h3>Deine Ideen für später.</h3><p>Tippe auf das Herz einer Übung. Sie bleibt auf diesem Gerät in deiner Merkliste.</p></div>';
};
$('allDrills').onclick=()=>setFavoriteFilter(false);$('favoriteDrills').onclick=()=>setFavoriteFilter(true);
function setFavoriteFilter(active){favoritesOnly=active;for(const [id,on]of [['allDrills',!active],['favoriteDrills',active]]){$(id).classList.toggle('active',on);$(id).setAttribute('aria-pressed',String(on));}renderCards();}
$('cards').onclick=ev=>{const f=ev.target.closest('[data-favorite]'),a=ev.target.closest('[data-add]'),d=ev.target.closest('[data-detail]');if(f){const id=f.dataset.favorite;uiPrefs.favorites=uiPrefs.favorites.includes(id)?uiPrefs.favorites.filter(x=>x!==id):[...uiPrefs.favorites,id];saveUI();renderCards();notify(uiPrefs.favorites.includes(id)?'In deiner Merkliste.':'Aus der Merkliste entfernt.');return;}if(a){add(a.dataset.add);return;}if(d){openDetail(d.dataset.detail);return;}const card=ev.target.closest('.dynamic-card');if(card&&!ev.target.closest('button,a,input'))openDetail(card.dataset.drag);};
function detailOrder(){const shown=[...$('cards').querySelectorAll('[data-drag]')].map(c=>c.dataset.drag);return shown.includes(detailId)?shown:[...SEED,...state.custom].map(e=>e.id);}
function stopPreview(){clearInterval(detailLoop);detailLoop=null;detailPlaying=false;$('detailDialog').classList.remove('preview-playing');const b=$('previewPlay');if(b){b.textContent='▶ Vorschau';b.setAttribute('aria-pressed','false');}}
function openDetail(id){if(!exercise(id))return;stopPreview();detailId=id;detailStep=0;detailReturnFocus=document.activeElement;renderDetail();$('detailDialog').scrollTop=0;if(!$('detailDialog').open)$('detailDialog').showModal();}
showLiveDetail=e=>openDetail(e.id);
function renderDetail(){const e=exercise(detailId),steps=stepsFor(e),order=detailOrder(),index=order.indexOf(e.id);$('detailDialog').setAttribute('aria-labelledby','detailTitle');$('detailContent').innerHTML=`<div class="detail-top"><span class="eyebrow">ÜBUNG ${index+1} / ${order.length}</span><button id="detailClose" class="closeDialog detail-header-close" aria-label="Detailansicht schließen">✕</button></div><div class="detail-heading"><span class="tag">${esc(e.tag)}</span><h2 id="detailTitle">${esc(e.name)}</h2><div class="detail-facts"><span>${e.minutes} Min</span><span>${e.min===e.max?e.min:e.min+'-'+e.max} Spieler / Gruppe</span><span>ab ${esc(e.ages[0])}</span></div></div><div class="detail-grid"><div class="detail-visual">${pitch(e,true)}<div class="preview-controls"><button id="previewPlay" aria-pressed="false">▶ Vorschau</button><span>Illustration · ${sceneFor(e)==='custom'?'neutraler Platzhalter':'schematisch'}</span></div><p class="sketch-disclaimer">Die Skizze zeigt den schematischen Aufbau. Der hervorgehobene Marker ist eine Orientierungshilfe zum Schritt, keine Bewegungssimulation: keine maßstabsgetreuen Positionen oder exakten Laufwege. Bei Torwartübungen keine Fang- oder Falltechnik-Demonstration.</p><div class="step-selector" aria-label="Ablaufschritte">${steps.map((s,i)=>`<button data-preview-step="${i}" aria-label="Schritt ${i+1}" aria-pressed="${i===detailStep}">${i+1}</button>`).join('')}</div><div id="previewCaption" class="preview-caption" aria-live="polite"></div></div><div class="detail-notes"><section><h3>01 / Ablauf</h3><ol class="coaching-steps">${steps.map(s=>`<li>${esc(s)}</li>`).join('')}</ol></section><section><h3>02 / Aufbau & Material</h3><div class="equipment-pills">${e.equipment.map(([n,c])=>`<span><strong>${c}</strong> ${esc(n)}</span>`).join('')}</div><p class="subtle">Je Gruppe · ${fit(e)?fit(e)+' parallele Gruppe(n) für '+plan().people+' Spieler':'⚠ Gruppengröße im Plan anpassen'}${e.type==='keeper'&&e.min<=2?' · Helfer zusätzlich':''}</p></section><section class="coaching-note"><h3>03 / Coaching & Sicherheit</h3><p>${esc(e.coaching)}</p></section><section><h3>04 / Einordnen</h3><p class="subtle">Eigene Kurzfassung / Variante. Altersklasse, Minuten und Mengen sind Vorschläge. Belastung und Abstände an Können anpassen. ${e.custom?'Deine eigene Übung.':''}</p>${e.url?`<a class="source-link" href="${esc(e.url)}" target="_blank" rel="noopener noreferrer">Fachliche Quelle öffnen ↗</a>`:'<p class="subtle">Keine externe Quelle hinterlegt.</p>'}</section></div></div><div class="detail-bottom"><div class="detail-paging"><button id="detailPrev" aria-label="Vorherige Übung" ${index<=0?'disabled':''}>←</button><span>${index+1} / ${order.length}</span><button id="detailNext" aria-label="Nächste Übung" ${index>=order.length-1?'disabled':''}>→</button></div><button id="detailAdd" class="primary">＋ In den Plan</button></div>`;
 $('detailClose').onclick=()=>$('detailDialog').close();$('detailAdd').onclick=()=>{add(e.id);$('detailAdd').textContent='✓ Hinzugefügt';};$('detailPrev').onclick=()=>neighborDetail(-1);$('detailNext').onclick=()=>neighborDetail(1);$('previewPlay').onclick=()=>{if(detailPlaying){stopPreview();return;}detailPlaying=true;$('detailDialog').classList.add('preview-playing');$('previewPlay').textContent='Ⅱ Pause';$('previewPlay').setAttribute('aria-pressed','true');detailLoop=setInterval(()=>{detailStep=(detailStep+1)%steps.length;updateStep();},3500);};document.querySelectorAll('[data-preview-step]').forEach(b=>b.onclick=()=>{stopPreview();detailStep=Number(b.dataset.previewStep);updateStep();});updateStep();
}
function updateStep(){const e=exercise(detailId);if(!e)return;const steps=stepsFor(e);$('previewCaption').textContent=`${detailStep+1}. ${steps[detailStep]}`;document.querySelectorAll('[data-preview-step]').forEach(b=>{const on=Number(b.dataset.previewStep)===detailStep;b.classList.toggle('active',on);b.setAttribute('aria-pressed',String(on));});$('detailDialog').dataset.step=String(detailStep);const visual=$('detailDialog').querySelector('.pitch-large');if(visual)visual.outerHTML=drillPitch(e,true,detailStep);$('detailDialog').querySelectorAll('.coaching-steps li').forEach((li,i)=>li.classList.toggle('current-step',i===detailStep));}
function neighborDetail(direction){const ids=detailOrder(),id=ids[ids.indexOf(detailId)+direction];if(id){stopPreview();detailId=id;detailStep=0;renderDetail();$('detailDialog').scrollTop=0;$('detailClose').focus({preventScroll:true});}}
$('detailDialog').addEventListener('close',()=>{stopPreview();detailReturnFocus?.isConnected&&detailReturnFocus.focus();});
$('detailDialog').addEventListener('keydown',ev=>{if(ev.target.closest('input,textarea'))return;if(ev.key==='ArrowRight'){ev.preventDefault();neighborDetail(1);}if(ev.key==='ArrowLeft'){ev.preventDefault();neighborDetail(-1);}});
let touchOrigin=null;$('detailDialog').addEventListener('touchstart',ev=>{if(ev.target.closest('button,a'))return;touchOrigin={x:ev.touches[0].clientX,y:ev.touches[0].clientY};},{passive:true});$('detailDialog').addEventListener('touchend',ev=>{if(!touchOrigin)return;const dx=ev.changedTouches[0].clientX-touchOrigin.x,dy=ev.changedTouches[0].clientY-touchOrigin.y;touchOrigin=null;if(Math.abs(dx)>85&&Math.abs(dy)<45)neighborDetail(dx<0?1:-1);},{passive:true});
// Keep a running block alive when browsing or adding another drill.
const v4Add=add;add=function(id){const running=deadline,seconds=remaining,index=timerIndex;v4Add(id);if(running){timerIndex=index;deadline=running;remaining=seconds;tick=setInterval(updateClock,200);renderTimer();}renderHome();};
const v4RenderTimer=renderTimer;renderTimer=function(){v4RenderTimer();$('liveView').classList.toggle('timer-running',!!deadline);$('startTimer').setAttribute('aria-pressed',String(!!deadline));};
// Useful action feedback without turning every tick into a notification.
for(const [id,message]of [['newPlan','Neue Einheit angelegt.'],['resetTimer','Timer zurückgesetzt.'],['nextBlock','Nächster Block bereit.']]){const original=$(id).onclick;$(id).onclick=ev=>{original(ev);notify(message);};}
const startAction=$('startTimer').onclick;$('startTimer').onclick=ev=>{startAction(ev);notify(deadline?'Training läuft.':'Timer pausiert.');};
const blockAction=$('blocks').onclick;$('blocks').onclick=ev=>{const remove=ev.target.closest('[data-remove]');if(!remove){blockAction(ev);if(ev.target.closest('[data-move]'))notify('Reihenfolge aktualisiert.');return;}const p=plan(),pos=p.blocks.findIndex(b=>b.id===remove.dataset.remove),block=p.blocks[pos];blockAction(ev);notify('Übung entfernt.');const undo=document.createElement('button');undo.textContent='Rückgängig';undo.onclick=()=>{if(!state.plans.includes(p)||p.blocks.some(b=>b.id===block.id))return;p.blocks.splice(Math.min(pos,p.blocks.length),0,block);save();resetTimer();render();notify('Übung wieder im Plan.');};$('status').append(undo);};
const prefs=document.createElement('section');prefs.className='display-prefs';prefs.innerHTML='<h3>Dein App-Gefühl</h3><label class="toggle-row">Animationen <input id="motionSetting" type="checkbox"></label><label class="toggle-row">Vibration bei Aktionen <input id="hapticSetting" type="checkbox"></label><p class="subtle">System-Einstellung für weniger Bewegung hat Vorrang. Vibration nur auf unterstützten Geräten. Merkliste und Darstellung bleiben auf diesem Gerät, separat vom Plan-Backup.</p>';$('info').append(prefs);$('motionSetting').checked=uiPrefs.motion;$('hapticSetting').checked=uiPrefs.haptics;
$('motionSetting').onchange=()=>{uiPrefs.motion=$('motionSetting').checked;applyUI();saveUI();if(reduced())stopPreview();notify(uiPrefs.motion?'Animationen eingeschaltet.':'Ruhige Darstellung eingeschaltet.');};$('hapticSetting').onchange=()=>{uiPrefs.haptics=$('hapticSetting').checked;saveUI();notify(uiPrefs.haptics?'Vibration aktiviert, falls unterstützt.':'Vibration ausgeschaltet.');};
document.addEventListener('click',ev=>{const b=ev.target.closest('button');if(!b||b.disabled)return;if(uiPrefs.haptics&&navigator.vibrate)navigator.vibrate(8);if(!reduced()&&b.animate)b.animate([{opacity:.65},{opacity:1}],{duration:220});},true);
function connectionState(){document.body.classList.toggle('is-offline',!navigator.onLine);$('connectionBadge').textContent=navigator.onLine?'LOKAL & BEREIT':'OFFLINE · LOKAL';}
const badge=document.createElement('span');badge.id='connectionBadge';badge.className='connection-badge';document.querySelector('header .brand').after(badge);window.addEventListener('online',()=>{connectionState();notify('Wieder online. Deine Pläne bleiben lokal.');});window.addEventListener('offline',()=>{connectionState();notify('Offline. Weiter trainieren.');});connectionState();
render();
// Rebind filters to the latest card renderer, including typing and imported profiles.
$('search').oninput=()=>renderCards();for(const id of ['filter','typeFilter','ageFilter','smart'])$(id).onchange=()=>renderCards();
