'use strict';
// Rules, previews and exports run entirely on this device.
const builder=document.createElement('section');builder.className='smart-builder';builder.innerHTML=`<div class="builder-heading"><span class="eyebrow">TRAINR / PLANASSISTENT</span><h3>Ein roter Faden für deine Einheit.</h3><p>Du gibst den Rahmen vor. Wir schlagen vor, du entscheidest.</p></div><div class="builder-fields"><label>Schwerpunkt<select id="buildFocus">${options(['Alle',...TAGS.filter(t=>t!=='Falltechnik')])}</select></label><label>Minuten inklusive Pausen<input id="buildMinutes" type="number" min="20" max="120" value="60"></label><label>Spieler ohne Trainer<input id="buildPeople" type="number" min="1" max="40" value="12"></label><label>Altersklasse<select id="buildAge">${options(AGES)}</select></label></div><p class="subtle" id="builderType"></p><button id="buildPreview" class="primary">✦ Plan vorschlagen</button><div id="buildResult" aria-live="polite"></div>`;
$('planner').querySelector('.planner-actions').before(builder);
const exportButtons=document.createElement('div');exportButtons.className='row';exportButtons.innerHTML='<button id="exportImage">↓ Plan als Bild (PNG)</button><button id="exportPdf">↓ Plan als PDF</button>';$('planner').querySelector('.export-drawer').append(exportButtons);
let proposed=null,builderReady=false;
function syncBuilder(){if(!state.profile)return;if(!builderReady){$('buildAge').value=state.profile.age;$('buildPeople').value=plan().people;$('buildFocus').value=plan().focus;$('buildMinutes').value=slot()?Math.min(120,Math.max(20,time(slot().end)-time(slot().start))):60;builderReady=true;}$('builderType').textContent=LABELS[state.profile.type]+' aus deinem Profil · keine KI, keine Datenübertragung.';}
function candidateGroups(e,n){for(let g=1;g<=n;g++)if(n>=g*e.min&&n<=g*e.max)return g;return 0;}
function makeProposal({age,people,minutes,focus,type}){
 if(!AGES.includes(age)||!integer(people,1,40)||!integer(minutes,20,120))throw Error('20-120 Minuten und 1-40 Spieler wählen.');
 const candidates=SEED.filter(e=>e.ages.includes(age)&&(type==='both'||e.type===type)&&candidateGroups(e,people)&&e.tag!=='Falltechnik');
 if(!candidates.length)throw Error('Keine sichere Kombination für dieses Profil. Bei Bambini allgemeine Ballspiele statt feste Torwartrollen wählen.');
 const stages=type==='keeper'?[['Aufwärmen','Aufwärmen'],['Technik',focus==='Alle'?'Fangen':focus],['Anwenden','Spieleröffnung']]:[['Aufwärmen','Aufwärmen'],['Schwerpunkt',focus==='Alle'?'Dribbling':focus],['Verbinden','Passspiel'],['Abschlussspiel','Spielform']];
 const used=new Set(),blocks=[];
 for(const [phase,tag] of stages){let eligible=candidates.filter(e=>!used.has(e.id)&&e.tag===tag);if(!eligible.length&&phase!=='Aufwärmen'&&phase!=='Abschlussspiel')eligible=candidates.filter(e=>!used.has(e.id)&&e.tag!=='Aufwärmen');if(!eligible.length)throw Error('Für diese Gruppengröße fehlt ein passender '+phase+'-Block. Spielerzahl oder Trainerart ändern, oder manuell planen.');
 eligible.sort((a,b)=>(candidateGroups(a,people)-candidateGroups(b,people))||a.name.localeCompare(b.name));const e=eligible[0];used.add(e.id);blocks.push({exerciseId:e.id,phase,groups:candidateGroups(e,people),why:e.tag===tag?phase+' mit '+e.tag:phase+': '+tag+' nicht passend verfügbar, Alternative '+e.tag});}
 // Time budgets include changes, drink breaks and explanations, not uninterrupted load.
 const weights=blocks.length===3?[.2,.4,.4]:[.18,.30,.22,.30];let left=minutes;blocks.forEach((b,i)=>{b.minutes=i===blocks.length-1?left:Math.round(minutes*weights[i]);left-=b.minutes;b.why+=' · '+b.groups+' parallele Gruppe(n), '+age+' · '+b.minutes+' Min inklusive Pause/Wechsel';});
 return {age,people,minutes,focus,type,blocks};
}
function previewProposal(){proposed=null;$('buildResult').replaceChildren();try{proposed=makeProposal({age:$('buildAge').value,people:Number($('buildPeople').value),minutes:Number($('buildMinutes').value),focus:$('buildFocus').value,type:state.profile?.type||'field'});$('buildResult').innerHTML=`<div class="proposal-top"><strong>${proposed.minutes} Minuten · ${proposed.age}</strong><span>${proposed.blocks.length} Blöcke</span></div><ol class="proposal-list">${proposed.blocks.map(b=>`<li><span class="tag">${esc(b.phase)}</span><h4>${esc(exercise(b.exerciseId).name)} <small>${b.minutes} Min</small></h4><p>${esc(b.why)}</p><button data-proposal-detail="${esc(b.exerciseId)}">Übung ansehen ↗</button></li>`).join('')}</ol><p class="subtle">Ein Vorschlag, keine Belastungsvorgabe. Gruppeneinteilung, Können, Helfer und Material prüfen. Trink- und Wechselpausen in jedem Block einplanen. Längere Blöcke in kurze Runden aufteilen; die Karten zeigen die empfohlene Rundendauer. Falltechnik wird nie automatisch gewählt.${proposed.type==='both'?' Feld- und Keepergruppen bei Bedarf separat planen.':''}</p><button id="buildApply" class="primary">Als neue Einheit übernehmen</button><p class="subtle">Deine bisherigen Einheiten bleiben unverändert. Danach Minuten und Reihenfolge frei ändern.</p>`;$('buildApply').onclick=applyProposal;document.querySelectorAll('[data-proposal-detail]').forEach(b=>b.onclick=()=>openDetail(b.dataset.proposalDetail));notify('Vorschlag bereit. Erst prüfen, dann übernehmen.');}catch(e){$('buildResult').innerHTML='<p class="notice" role="alert">'+esc(e.message)+'</p>';}}
function applyProposal(){if(!proposed)return;if(deadline)return notify('Erst den laufenden Timer pausieren.');if(state.plans.length>=100)return notify('Maximal 100 Einheiten.');const draftPlan={id:uid(),name:(proposed.focus==='Alle'?'Abwechslungsreiche Einheit':proposed.focus)+' · '+proposed.age,people:proposed.people,age:proposed.age,slot:plan().slot,focus:proposed.focus,blocks:proposed.blocks.map(b=>({id:uid(),exerciseId:b.exerciseId,minutes:b.minutes}))};state.plans.push(draftPlan);state.selected=draftPlan.id;resetTimer();save();render();$('buildResult').innerHTML='<p class="notice">✓ Neue Einheit erstellt. Minuten, Reihenfolge und Übungen kannst du unten ändern.</p>';proposed=null;notify('Neue Einheit übernommen. Bestehende Pläne bleiben erhalten.');}
$('buildPreview').onclick=previewProposal;['buildFocus','buildMinutes','buildPeople','buildAge'].forEach(id=>$(id).addEventListener('input',()=>{proposed=null;$('buildResult').innerHTML='<p class="subtle">Rahmen geändert. Neuen Vorschlag erstellen.</p>';}));
const v5Render=render;render=function(){v5Render();syncBuilder();};syncBuilder();
const v5Cards=renderCards;renderCards=function(){v5Cards();$('suggestionNote').textContent=$('suggestionNote').textContent.replace('Keine automatische Plan-Erstellung.','Planassistent im Bereich Plan: Vorschlag prüfen und übernehmen.');};renderCards();
// Rasterized A4 pages: locally generated PDF, no external libraries or remote fonts.
function drawExportPages(){const p=plan();if(!p.blocks.length)throw Error('Erst Übungen zum Plan hinzufügen.');const pages=[];let c,x,y,pageNum=0;const W=1240,H=1754,pad=82;
 function newPage(){c=document.createElement('canvas');c.width=W;c.height=H;x=c.getContext('2d');x.fillStyle='#f8faf7';x.fillRect(0,0,W,H);x.fillStyle='#11231b';x.font='bold 30px system-ui';x.fillText('TRAINR / TRAININGSPLAN',pad,85);x.fillStyle='#254d38';x.fillRect(pad,108,W-pad*2,5);y=165;pages.push(c);pageNum++;}
 function lines(t,size=23,bold=false,color='#22352b'){x.font=(bold?'bold ':'')+size+'px system-ui';x.fillStyle=color;const out=[];for(const raw of String(t).split('\n')){let line='';for(const word of raw.split(' ').flatMap(w=>w.match(/.{1,55}/g)||[''])){if(x.measureText(line+word).width>W-pad*2&&line){out.push(line.trim());line='';}line+=word+' ';}out.push(line.trim());}return out;}
 function write(t,size=23,bold=false,color='#22352b'){const ls=lines(t,size,bold,color);for(const l of ls){if(y>H-120)newPage();x.font=(bold?'bold ':'')+size+'px system-ui';x.fillStyle=color;x.fillText(l,pad,y);y+=Math.round(size*1.5);}}
 newPage();write(p.name,36,true);write((p.age||state.profile?.age||'')+' · '+p.people+' Spieler · '+p.blocks.reduce((a,b)=>a+b.minutes,0)+' Min',24);write(slot()?DAYS[slot().day]+' · '+slot().start+'-'+slot().end:'',22);y+=20;
 p.blocks.forEach((b,i)=>{const e=exercise(b.exerciseId);if(y>H-500)newPage();write(String(i+1).padStart(2,'0')+' / '+e.name+' · '+b.minutes+' Min',28,true);write(e.tag+' · '+(fit(e)?fit(e)+' parallele Gruppe(n)':'WARNUNG: Gruppengröße prüfen'),21,true,'#376847');write(e.description);write('Coaching: '+e.coaching,21);write('Je Gruppe: '+e.equipment.map(a=>a[1]+' '+a[0]).join(' · '),21);write('Quelle: '+(e.url||'Eigene Übung'),17);if(!e.ages.includes(p.age||state.profile?.age))write('WARNUNG: Altersklasse passt nicht.',21,true);y+=26;});
 if(y>H-430)newPage();write('Materialübersicht',28,true);write(Object.entries(requirements()).map(([n,q])=>q+' '+n).join(' · '),23);write('Höchstbedarf, nicht Summe. Bei unpassender Gruppengröße sind Mengen vorläufig. Keeper mit 1-2 Spielern: Helfer zusätzlich. Minuten inklusive Pausen und Wechsel; Belastung selbst anpassen. Altersgrenzen und Mengen sind Vorschläge. Sichere Anleitung, freie Schusswege und geeigneter Boden sind Pflicht.',21);pages.forEach((page,i)=>{const ctx=page.getContext('2d');ctx.fillStyle='#52675a';ctx.font='18px system-ui';ctx.fillText('Lokal erstellt · Keine Konten · Seite '+(i+1)+' / '+pages.length,pad,H-50);});return pages;}
function pdfBytes(canvases){const enc=new TextEncoder(),chunks=[],offsets=[0];let pos=0;const push=s=>{const a=typeof s==='string'?enc.encode(s):s;chunks.push(a);pos+=a.length;};const objects=2+canvases.length*3;push('%PDF-1.4\n');function obj(n,s){offsets[n]=pos;push(n+' 0 obj\n'+s+'\nendobj\n');}obj(1,'<< /Type /Catalog /Pages 2 0 R >>');obj(2,'<< /Type /Pages /Count '+canvases.length+' /Kids ['+canvases.map((_,i)=>(3+i*3)+' 0 R').join(' ')+'] >>');canvases.forEach((c,i)=>{const n=3+i*3,raw=atob(c.toDataURL('image/jpeg',.92).split(',')[1]),bytes=Uint8Array.from(raw,z=>z.charCodeAt(0));obj(n,'<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595.28 841.89] /Resources << /XObject << /Im'+i+' '+(n+1)+' 0 R >> >> /Contents '+(n+2)+' 0 R >>');offsets[n+1]=pos;push((n+1)+' 0 obj\n<< /Type /XObject /Subtype /Image /Width 1240 /Height 1754 /ColorSpace /DeviceRGB /BitsPerComponent 8 /Filter /DCTDecode /Length '+bytes.length+' >>\nstream\n');push(bytes);push('\nendstream\nendobj\n');const s='q 595.28 0 0 841.89 0 0 cm /Im'+i+' Do Q';obj(n+2,'<< /Length '+enc.encode(s).length+' >>\nstream\n'+s+'\nendstream');});const start=pos;push('xref\n0 '+(objects+1)+'\n0000000000 65535 f \n');for(let i=1;i<=objects;i++)push(String(offsets[i]).padStart(10,'0')+' 00000 n \n');push('trailer\n<< /Size '+(objects+1)+' /Root 1 0 R >>\nstartxref\n'+start+'\n%%EOF');const out=new Uint8Array(pos);let k=0;chunks.forEach(a=>{out.set(a,k);k+=a.length;});return out;}
let exportPages=[],exportKind='pdf';const exportDialog=document.createElement('dialog');exportDialog.id='exportDialog';exportDialog.className='export-preview';exportDialog.innerHTML='<div class="row"><h2>Dein Plan zum Mitnehmen.</h2><button id="exportClose" aria-label="Export schließen">✕</button></div><p id="exportNote"></p><div id="exportPreviewPages"></div><button id="exportDownload" class="primary">Herunterladen</button>';document.body.append(exportDialog);$('exportClose').onclick=()=>exportDialog.close();
function prepareExport(kind){try{exportPages=drawExportPages();exportKind=kind;$('exportNote').textContent=exportPages.length+' Seite(n) · lokal erstellt. '+(kind==='png'?'Jede Seite als eigene PNG-Datei; bei vielen Seiten ist PDF einfacher.':'Ein PDF mit allen Seiten. Text im PDF ist als Bild eingebettet.');$('exportPreviewPages').replaceChildren(...exportPages);exportDialog.showModal();}catch(e){notify(e.message);}}
$('exportImage').onclick=()=>prepareExport('png');$('exportPdf').onclick=()=>prepareExport('pdf');$('exportDownload').onclick=()=>{if(exportKind==='pdf'){download('TRAINR-Plan.pdf',pdfBytes(exportPages),'application/pdf');notify('PDF erstellt.');}else{for(let i=0;i<exportPages.length;i++){const a=document.createElement('a');a.download='TRAINR-Plan-'+(i+1)+'.png';a.href=exportPages[i].toDataURL('image/png');a.click();}notify('PNG erstellt. Browser kann bei mehreren Dateien nachfragen.');}};
