'use strict';
// One session workspace. Storage keys and existing records are unchanged.
const easy=document.createElement('section');easy.className='easy-session';easy.innerHTML=`<span class="eyebrow">DEIN TRAINING IN EINEM SCHRITT</span><h2>Was steht heute an?</h2><div class="easy-fields"><label>Schwerpunkt<select id="easyFocus">${options(['Alle',...TAGS.filter(t=>t!=='Falltechnik')])}</select></label><label>Minuten<input id="easyMinutes" type="number" min="20" max="120"></label><label>Spieler<input id="easyPeople" type="number" min="1" max="40"></label></div><details id="easyOptions"><summary>Alter & weitere Optionen</summary><label>Altersklasse<select id="easyAge">${options(AGES)}</select></label><p id="easyProfile" class="subtle"></p><button id="easyManual">Manuell planen / gespeicherte Einheiten</button><button id="easyPreview">Ausführlichen Vorschlag prüfen</button></details><button id="easyCreate" class="primary">✦ Einheit erstellen</button><p id="easyError" role="alert"></p><p class="subtle">Neue Einheit, ohne alte Pläne zu ersetzen. Zeiten enthalten Erklärungen, Pausen und Wechsel. Material, Platz und Können vor Ort prüfen.</p>`;$('homeView').querySelector('.welcome').after(easy);
const easyFrameDrawer=document.createElement('details');easyFrameDrawer.className='easy-frame-drawer';easyFrameDrawer.innerHTML='<summary>＋ Neue Einheit planen</summary>';easy.before(easyFrameDrawer);easyFrameDrawer.append(easy);
$('homeView').querySelector('.welcome p:last-child').textContent='Rahmen wählen. Einheit anpassen. Loslegen.';
// Keep the old ticket and its controls, but remove it as an obligatory screen.
const saved=document.createElement('details');saved.className='easy-saved';saved.innerHTML='<summary>Gespeicherte Einheiten & Planübersicht</summary>';$('homePlan').before(saved);saved.append($('homePlan'));
const oldQuick=$('quickBrowse').closest('.quick-row');oldQuick.style.display='none';
$('homeExplore').textContent='＋ Übung ergänzen';
const easyTools=document.createElement('div');easyTools.className='easy-tools';easyTools.innerHTML='<button id="easyUndo" hidden>Letzte Änderung zurück</button><button id="easyMore">Notizen, Gruppen & Export</button>';$('homeTimeline').after(easyTools);
const previewDrawer=document.createElement('details');previewDrawer.className='easy-advanced';previewDrawer.innerHTML='<summary>Ausführlicher Planassistent</summary>';builder.before(previewDrawer);previewDrawer.append(builder);
const coachDrawer=document.createElement('details');coachDrawer.className='easy-advanced';coachDrawer.innerHTML='<summary>Coaching-Ziel & Gruppen</summary>';coachBox.before(coachDrawer);coachDrawer.append(coachBox);
let easySelected=null,easyUndo=null;
function easySync(){const p=plan();const key=p.id+'|'+JSON.stringify(state.profile);if(easySelected!==key){easySelected=key;easyFrameDrawer.open=!p.blocks.length;easyFrameDrawer.classList.toggle('is-empty',!p.blocks.length);$('easyFocus').value=p.focus;$('easyPeople').value=Math.min(40,p.people);$('easyAge').value=p.age||state.profile?.age||'E-Jugend';$('easyMinutes').value=p.blocks.length?Math.min(120,Math.max(20,p.blocks.reduce((n,b)=>n+b.minutes,0))):slot()?Math.min(120,Math.max(20,time(slot().end)-time(slot().start))):60;easyUndo=null;}
 $('easyProfile').textContent=(LABELS[state.profile?.type]||'Trainerart im Profil wählen')+' · Zeiten und Spielerzahl kannst du oben ändern.';
 $('easyCreate').textContent=p.blocks.length?'✦ Neue Einheit erstellen':'✦ Einheit erstellen';
 $('easyUndo').hidden=!easyUndo;
 $('homeCount').textContent=p.blocks.length?p.blocks.reduce((n,b)=>n+b.minutes,0)+' Min · '+p.people+' Spieler':'Noch keine Einheit';
 $('homeTimeline').innerHTML=p.blocks.length?p.blocks.map((b,i)=>`<article class="easy-block" data-easy-block="${b.id}"><div class="easy-block-title"><span class="num">${i+1}</span><button data-edit-block="${b.id}" aria-label="${esc(exercise(b.exerciseId).name)} bearbeiten"><strong>${esc(exercise(b.exerciseId).name)}</strong><small>${esc(exercise(b.exerciseId).tag)}${b.people?" · "+b.people+" Spieler":""} · Bearbeiten ✎</small></button></div><div class="easy-block-controls"><div class="easy-stepper"><button data-easy-time="${b.id}" data-delta="-1" aria-label="Block ${i+1} eine Minute kürzer" ${b.minutes<=1?'disabled':''}>−</button><span>${b.minutes} Min</span><button data-easy-time="${b.id}" data-delta="1" aria-label="Block ${i+1} eine Minute länger" ${b.minutes>=120?'disabled':''}>＋</button></div><button data-easy-swap="${b.id}">↻ Tauschen</button></div></article>`).join(''):'<div class="easy-empty">Oben einmal „Einheit erstellen“ antippen. Danach stehen alle Blöcke direkt hier.</div>';
}
const easyHome=renderHome;renderHome=function(){easyHome();easySync();};
function easyFrame(){return {age:$('easyAge').value,people:Number($('easyPeople').value),minutes:Number($('easyMinutes').value),focus:$('easyFocus').value,type:state.profile?.type||'field'};}
function easyGuard(){if(deadline){notify('Erst den laufenden Timer pausieren.');return false;}return true;}
$('easyCreate').onclick=()=>{if(!easyGuard())return;$('easyError').textContent='';try{if(state.plans.length>=100)throw Error('Maximal 100 Einheiten. Alte Einheiten unter Plan verwalten.');proposed=makeProposal(easyFrame());applyProposal();view('home',{scroll:false});$('homeTimeline').scrollIntoView({behavior:reduced()?'instant':'smooth',block:'start'});if(!reduced())$('homeTimeline').animate([{opacity:.2,transform:'translateY(16px)'},{opacity:1,transform:'none'}],{duration:420});}catch(e){$('easyError').textContent=e.message;}};
$('easyManual').onclick=()=>{view('planner');$('planSettings').open=true;};
$('easyPreview').onclick=()=>{const f=easyFrame();$('buildFocus').value=f.focus;$('buildAge').value=f.age;$('buildPeople').value=f.people;$('buildMinutes').value=f.minutes;view('planner');previewDrawer.open=true;previewProposal();builder.scrollIntoView({block:'start'});};
$('easyMore').onclick=()=>{view('planner');coachDrawer.open=true;};
$('homeStart').onclick=()=>{if(!plan().blocks.length)return;view('live');if(!deadline)$('startTimer').onclick();};
function rememberEasy(){easyUndo={planId:plan().id,blocks:structuredClone(plan().blocks)};}
function changedEasy(message){resetTimer();save();render();notify(message);}
$('homeTimeline').onclick=ev=>{const detail=ev.target.closest('[data-easy-detail]'),swap=ev.target.closest('[data-easy-swap]'),step=ev.target.closest('[data-easy-time]');if(detail){openDetail(detail.dataset.easyDetail);return;}if(!swap&&!step)return;if(!easyGuard())return;const b=plan().blocks.find(b=>b.id===(swap?.dataset.easySwap||step?.dataset.easyTime));if(!b)return;
 if(step){const n=b.minutes+Number(step.dataset.delta);if(!integer(n,1,120))return;rememberEasy();b.minutes=n;changedEasy('Blockzeit geändert.');return;}
 const e=exercise(b.exerciseId),used=new Set(plan().blocks.map(x=>x.exerciseId));const candidates=[...SEED,...state.custom].filter(x=>!used.has(x.id)&&x.tag===e.tag&&x.tag!=='Falltechnik'&&x.ages.includes(plan().age||state.profile?.age)&&(state.profile?.type==='both'||x.type===state.profile?.type)&&fit(x));if(!candidates.length)return notify('Keine weitere passende Übung. Über „Übung ergänzen“ manuell wählen.');rememberEasy();b.exerciseId=candidates[0].id;changedEasy('Übung getauscht. Blockzeit bleibt gleich.');};
$('easyUndo').onclick=()=>{if(!easyGuard()||!easyUndo||easyUndo.planId!==plan().id)return;plan().blocks=easyUndo.blocks;easyUndo=null;changedEasy('Änderung zurückgenommen.');};
// Small local add sheet, not another mandatory library/filter journey.
const addSheet=document.createElement('dialog');addSheet.id='easyAddDialog';addSheet.innerHTML='<h2>Übung ergänzen</h2><p class="subtle">Passend zu Alter, Trainerart und Spielerzahl. Neue Blöcke verlängern deine Einheit.</p><div id="easyAddList"></div><button id="easyLibrary">Alle Übungen & eigene Übungen</button><button id="easyAddClose">Schließen</button>';document.body.append(addSheet);v16Sheetify(addSheet);
function openEasyAdd(){if(!easyGuard())return;const used=new Set(plan().blocks.map(b=>b.exerciseId));const list=[...SEED,...state.custom].filter(e=>!used.has(e.id)&&e.tag!=='Falltechnik'&&e.ages.includes(plan().age||state.profile?.age)&&(state.profile?.type==='both'||e.type===state.profile?.type)&&fit(e)).sort((a,b)=>(b.tag===plan().focus)-(a.tag===plan().focus));$('easyAddList').innerHTML=list.slice(0,6).map(e=>`<button data-easy-add="${e.id}"><strong>＋ ${esc(e.name)}</strong><small>${esc(e.tag)} · ${effective(e).minutes} Min</small></button>`).join('')||'<p>Keine passende Auswahl. In der Bibliothek manuell planen.</p>';addSheet.showModal();}
$('homeExplore').onclick=openEasyAdd;$('planAdd').onclick=openEasyAdd;
$('easyAddList').onclick=ev=>{const b=ev.target.closest('[data-easy-add]');if(!b||!easyGuard())return;if(plan().blocks.length>=100)return notify('Maximal 100 Blöcke.');rememberEasy();add(b.dataset.easyAdd);addSheet.close();render();};
$('easyLibrary').onclick=()=>{addSheet.close();view('library');};$('easyAddClose').onclick=()=>addSheet.close();
renderHome();
