'use strict';
const APP_VERSION='18.0.0';
const versionBadge=document.createElement('button');versionBadge.id='versionBadge';versionBadge.className='version-badge';versionBadge.textContent='V18 · 18.0.0';versionBadge.title='Nach Updates suchen';versionBadge.setAttribute('aria-label','Version 18.0.0, nach Updates suchen');$('connectionBadge').after(versionBadge);
const updateBar=document.createElement('div');updateBar.id='updateBar';updateBar.className='hidden';updateBar.setAttribute('role','status');updateBar.innerHTML='<div><strong>Neue Version bereit.</strong><span>Deine gespeicherten Pläne bleiben erhalten. Laufendes Training zuerst pausieren.</span></div><button id="applyUpdate">Jetzt aktualisieren</button><button id="laterUpdate" aria-label="Update später anzeigen">Später</button>';document.body.append(updateBar);
let updateRegistration=null;
function showUpdate(){updateBar.classList.remove('hidden');}
$('laterUpdate').onclick=()=>updateBar.classList.add('hidden');
$('applyUpdate').onclick=()=>{if(deadline){notify('Training zuerst pausieren, dann aktualisieren.');return;}save();if(updateRegistration?.waiting)updateRegistration.waiting.postMessage({type:'SKIP_WAITING'});else location.reload();};
let askedReload=false;const hadController=!!navigator.serviceWorker?.controller;
if('serviceWorker'in navigator){navigator.serviceWorker.getRegistration().then(reg=>reg||navigator.serviceWorker.ready).then(reg=>{if(!reg)return;updateRegistration=reg;const watch=worker=>{if(!worker)return;worker.addEventListener('statechange',()=>{if(worker.state==='installed'&&navigator.serviceWorker.controller)showUpdate();});};if(reg.waiting)showUpdate();watch(reg.installing);reg.addEventListener('updatefound',()=>watch(reg.installing));reg.update().catch(()=>{});});navigator.serviceWorker.addEventListener('controllerchange',()=>{if(askedReload){location.reload();return;}if(hadController)showUpdate();});$('applyUpdate').addEventListener('click',()=>{if(!deadline)askedReload=true;});}
async function checkVersion(manual=false){if(!navigator.onLine){if(manual)notify('Offline. Updates brauchen eine Verbindung.');return;}try{const response=await fetch('./version.json',{cache:'no-store'});if(!response.ok)throw Error();const {version}=await response.json();if(version!==APP_VERSION)showUpdate();else if(manual)notify('V18 · 18.0.0 ist aktuell.');if(updateRegistration)await updateRegistration.update();}catch{if(manual)notify('Update-Prüfung gerade nicht möglich. Deine Pläne bleiben lokal.');}}
versionBadge.onclick=()=>checkVersion(true);window.addEventListener('online',()=>checkVersion());document.addEventListener('visibilitychange',()=>{if(!document.hidden)checkVersion();});checkVersion();
// Visible, bounded feedback. No particles stay in the DOM; reduced-motion wins.
const clickHalo=document.createElement('div');clickHalo.className='click-halo';clickHalo.setAttribute('aria-hidden','true');document.body.append(clickHalo);
document.addEventListener('dragstart',()=>{document.getAnimations().forEach(a=>a.cancel());},true);
document.addEventListener('click',ev=>{const control=ev.target.closest('button,summary,.dynamic-card,input[type=checkbox],input[type=radio]');if(!control||control.disabled||reduced())return;const rect=control.getBoundingClientRect(),x=ev.clientX||rect.left+rect.width/2,y=ev.clientY||rect.top+rect.height/2;clickHalo.style.left=x+'px';clickHalo.style.top=y+'px';clickHalo.getAnimations().forEach(a=>a.cancel());clickHalo.animate([{transform:'translate(-50%,-50%) scale(.2)',opacity:.8},{transform:'translate(-50%,-50%) scale(2.4)',opacity:0}],{duration:550,easing:'cubic-bezier(.2,.7,.3,1)'});const target=control.closest('.dynamic-card')||control;target.animate([{transform:'scale(.97)'},{transform:'scale(1.015)'},{transform:'scale(1)'}],{duration:380,easing:'ease-out'});},true);
const v6View=view;view=function(name,opts){v6View(name,opts);if(reduced())return;const id={home:'homeView',library:'library',planner:'planner',live:'liveView',info:'info'}[name];const target=$(id);if(target){target.getAnimations().forEach(a=>a.cancel());target.animate([{opacity:.2,transform:'translateY(22px)'},{opacity:1,transform:'translateY(0)'}],{duration:360,easing:'cubic-bezier(.2,.7,.3,1)'});}};
// Existing nav closures call view by name, so they use the updated transition.
const v6Notify=notify;notify=function(text){v6Notify(text);const modal=document.querySelector('dialog[open]');if(modal){let inline=modal.querySelector('.modal-feedback');if(!inline){inline=document.createElement('p');inline.className='modal-feedback';inline.setAttribute('role','status');modal.prepend(inline);}inline.textContent=text;clearTimeout(inline.feedbackTimeout);inline.feedbackTimeout=setTimeout(()=>inline.remove(),3500);}};
matchMedia('(prefers-reduced-motion: reduce)').addEventListener('change',()=>{if(reduced()){document.getAnimations().forEach(a=>a.cancel());stopPreview();}});

$('motionSetting').addEventListener('change',()=>{if(reduced())document.getAnimations().forEach(a=>a.cancel());});
